### PR TITLE
Putting up screenshots in table format

### PR DESCRIPTION
**Pull request by heysadboy**
Fixes https://github.com/fossasia/open-event-android/issues/1540

### CODE REVIEW

**Comment by m-murad** [comment]
There are multiple commits.
You need to rebase.

**Comment by iamareebjamal** [comment]
You can achieve this without table, try the suggestion given in the issue section. This method is shrinking the size of image

**Comment by iamareebjamal** [comment]
Please squash commits @heysadboy 

You should do it after each commit and not wait for someone else to say this, it wastes time :)

**Comment by iamareebjamal** [comment]
@heysadboy It's table again

**Pull request closed without merging**
