### PR TITLE
Added Chinese(zh)

### PR DESCRIPTION
**Pull request by seadog007**

### CODE REVIEW

**Comment by mananwason** [comment]
@seadog007 Could you squash the commits into one please?

**Comment by seadog007** [comment]
@mananwason Done

**Comment by mananwason** [comment]
@seadog007 I believe that values-zh and values-zh-rCN are for 2 different languages. Is this the case. If it is then I'd like them to be in different PR's. Thanks

**Comment by seadog007** [comment]
Well, that both are Chinese

**Comment by seadog007** [comment]
But if you want, fine :P

**Comment by mananwason** [comment]
I really don't know if they are different or same. I'll quote what you commented here.
'' zh-rCN -> China
 zh -> Hong Kong, Taiwan''

**Comment by Luolc** [comment]
Hi mananwason. Chinese use simplified(like `简体字`) and traditional(like `繁體字`) Chinese characters in different regions of the country. Thus it is supposed to build 2 different string values res for Chinese users.
It is a bit confused for foreigners of China~ :D 
Hope it helps.

**Pull request closed without merging**
