### PR TITLE
add selectable item background to list view's rows

### PR DESCRIPTION
**Pull request by ahmed-fathy-aly**
shows the default ripple background when you click on a row

### CODE REVIEW

**Comment by ahmed-fathy-aly** [comment]
@championswimmer  
Can you have a look at this pull request please ?

**Comment by the-dagger** [comment]
You should squash all the commits into one before sending a PR. @ahmed-fathy-aly 
Cheers.

**Comment by mananwason** [comment]
I believe @ahmed-fathy-aly is not working on this anymore. Closing this.

**Comment by the-dagger** [comment]
I'll try to have a look at what he was trying to do and if it looks good, i'll send a PR. 
Cheers

**Comment by mananwason** [comment]
:+1:

**Pull request closed without merging**
