### PR TITLE
Added Install/Config Instructions

### PR DESCRIPTION
**Pull request by MaxBorsch**
Added Install/Config Instructions

### CODE REVIEW

**Comment by mananwason** [comment]
@MaxBorsch Please squash the commits.

**Comment by MaxBorsch** [comment]
How do I squash commits that are already synced online / in a pull request?

**Comment by MaxBorsch** [comment]
@mananwason Squashed.

**Comment by mananwason** [comment]
Awesome @MaxBorsch. Cheers!

**Comment by championswimmer** [comment]
Looks good to me, nice job @MaxBorsch

**Pull request merged**
