### PR TITLE
fix UI and format date correctly of favorite item

### LINKED ISSUE #305: Format the date correctly of favorite item and fix UI of favorite item
Working on it :+1:

### PR DESCRIPTION
**Pull request by dreadpool2**
Fixes #305 

screenshot_20180711-213252

### CODE REVIEW

**Comment by simarsingh24** [comment]
this is not how Eventbrite shows it, if you fix something make sure we don't have spend time again on it.

**Comment by dreadpool2** [comment]
I used the same function used in About Event activity to format the date as even Eventbrite does that. Will change the function then

**Comment by simarsingh24** [comment]
when changing the function also look at different places the result gets reflected

**Comment by dreadpool2** [comment]
Yup :+1:

**Comment by dreadpool2** [comment]
screenshot_20180712-115838

**Comment by simarsingh24** [comment]
Why is there a `.` in test event and a `-` in others?

**Comment by dreadpool2** [comment]
@simarsingh24 Because I am utilising a bullet point in my format

**Comment by simarsingh24** [comment]
@dreadpool2 Thats not what i meant in some places there is `.` and `-` in others

**Comment by dreadpool2** [comment]
@simarsingh24 Yeah, actually in eventbrite they use both `-` and ` •` in format of date. They use the bullet foramatted date in about event activity and favorite item, whereas the bullet is not used in other formats

**Pull request merged**
