### PR TITLE
fix : App generated using zip is not able to fetch latest data

### LINKED ISSUE #1604: App generated using zip is not able to fetch latest data
**Actual Behaviour**

App generated using zip is not able to fetch updated/latest data because if app is generated using zip then api end point is null. Api end point is used to fetch latest data. 

**Expected Behaviour**

If app is generated using zip it should also able to fetch latest event data.

**Steps to reproduce it**

Generate app using zip file provided in [sample](https://github.com/fossasia/open-event/tree/master/sample)

**LogCat for the issue**

`GET http://abc//tracks http/1.1
 HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "abc": No address associated with hostname`

**Screenshots of the issue**

zip_error

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 4](https://github.com/fossasia/open-event-android/milestone/27)

### PR DESCRIPTION
**Pull request by Shailesh351**
Fixes #1604 

Changes: 
Used `root_url` from `meta` file and `id` from `event` file to create api endpoint for event. 
Like : `endpoint` = `root_url` + `/api/v1/events/`+ `{event_id}`

For testing update zip file.
For FOSSASIA2016 : 
- root_url : `https://eventyay.com/`
- id : `20`

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@Shailesh351 Please test the generated app from samples and check if working. I think it'll give 404 error

**Comment by Shailesh351** [comment]
@iamareebjamal Current samples won't work because they are not hosted on server.
Suppose as a organiser  you export event as zip file and this zip file should be able to generated working apk with ability to fetch latest data.

But in current all samples `root_url` is `http://open-event-dev.herokuapp.com/`. But actually this events are not created on this server.

I found FOSSASIA16 & FOSSASIA15 events on `eventyay.com`. So that in order to check if it is working or not i mentioned to update zip file.

FOSSASIA16 : 
`id` = 20    
https://eventyay.com/api/v1/events/20/event

FOSSASIA15 : `id` = 14
https://eventyay.com/api/v1/events/14/event

**Comment by iamareebjamal** [comment]
The problem is that what would be your strategy when a user creates zip by hand and expresses no desire of specifying or hosting a server?

**Comment by Shailesh351** [comment]
@iamareebjamal made changes. If user don't have server he/she should keep root_url.

**Comment by iamareebjamal** [comment]
@niranjan94 Please review

**Pull request merged**
