### PR TITLE
Added Doc for build

### PR DESCRIPTION
**Pull request by vipulroxx**

### CODE REVIEW

**Comment by creativepsyco** [comment]
The doc already exists please submit changes against original readme

**Comment by vipulroxx** [comment]
Please check :)

**Comment by creativepsyco** [comment]
@vipulroxx I don't see how this adds any value to the project. Please see existing issues to work on something, the README currently contains sufficient information for build purposes.

**Comment by vipulroxx** [comment]
@creativepsyco it was for a task in Google Code-in

**Comment by vipulroxx** [comment]
https://codein.withgoogle.com/dashboard/task-instances/5734095527084032/?sp-page=1

**Comment by mananwason** [comment]
@vipulroxx For the task, you are advised to add some documentation that makes the README better. One thing you can add is that you can point out which values to change in the styles.xml to change which components of the app. Take a look at the styles.xml here https://github.com/mananwason/open-event-android/tree/stylebranch and try to figure out what happens on changing each component. You can try to document that. Cheers!

**Comment by creativepsyco** [comment]
You can provide screenshots etc, that definitely makes it better right?

**Comment by vipulroxx** [comment]
@creativepsyco I added a folder in task for screenshot of my build process > https://drive.google.com/folderview?id=0B9thWab4XrNraFA5YWdwVk5JUzQ&usp=sharing

**Comment by creativepsyco** [comment]
Hi @vipulroxx All I am saying is that the first instance already added significant amount of information to the README regarding project setup, configuration variables etc. You should at least be able to match it's quality if not exceed it. I can't let you have an easy day here regarding contributing to an open source project.

**Comment by vipulroxx** [comment]
ohh... as suggested by @mananwason can I add some changes to Doc regarding the style.xml in the Readme?

**Comment by creativepsyco** [comment]
I don't know you can look at existing examples of documentation over different projects in GitHub and see how they ease things up for new contributors, thats the approach that would be preferable in the long run, to be as similar to the style followed by Big Open source projects. That would be quite good in my opinion.

**Pull request closed without merging**
