### PR TITLE
fix: Fixed FAB issue in Edit Profile

### LINKED ISSUE #1460: FAB in Edit Profile Not Working
**Describe the chore**
Floating Action Button not working in edit profile.
Fix it.
Screenshots:
axa

**Would you like to work on the issue?**

- [x] Yes

### PR DESCRIPTION
**Pull request by somenath1435**
Fixes #1460 

Changes: Fixed FAB issue in Edit Profile.

### CODE REVIEW

**Comment by somenath1435** [comment]
@iamareebjamal @liveHarshit @nikit19 please review

**Comment by somenath1435** [comment]
@liveHarshit those lines are for imageview not FAB

**Comment by liveHarshit** [comment]
Yes, remove them.

**Comment by somenath1435** [comment]
@liveHarshit Done

**Pull request merged**
