### PR TITLE
fix: Fix UI of ordered ticket item

### LINKED ISSUE #454: Fix the UI of item_card _order.xml
Working on it :+1:

### PR DESCRIPTION
**Pull request by dreadpool2**
Fixes #454 
screenshot_20180804-150447

### CODE REVIEW

**Comment by simarsingh24** [comment]
please add befor changes screen shot

**Comment by dreadpool2** [comment]
Before change
screenshot_20180804-182515

**Comment by dreadpool2** [comment]
Updated 
screenshot_20180804-191155

**Comment by nikit19** [comment]
@dreadpool2 As I commented earlier padding is fine. Just fix the width. This way the card looks too big. See how tickets fragment looks in Eventbrite

**Comment by dreadpool2** [comment]
@nikit19 Please check now :+1: 
screenshot_20180805-175358

**Comment by dreadpool2** [comment]
Removed hardcoding of widths :+1: 
screenshot_20180806-162023

**Comment by dreadpool2** [comment]
PR Udpated.

**Pull request merged**
