### PR TITLE
Managing screenshots in readme file

### PR DESCRIPTION
**Pull request by heysadboy**
Fixes https://github.com/fossasia/open-event-android/issues/1540

### CODE REVIEW

**Comment by heysadboy** [comment]
@iamareebjamal  I was not able to do it in previous pr due to lost commits, fixing them here.

**Comment by mahikaw** [comment]
@iamareebjamal @heysadboy the about page has been changed. Could you please take that into account too?

**Comment by iamareebjamal** [comment]
There are quite a few UI changes on the way, so let's wait for them to be merged and then we can add them in one PR @mahikaw ?

**Comment by mahikaw** [comment]
Sure @iamareebjamal that too sounds good. 👍

**Pull request merged**
