### PR TITLE
Update gradle plugin version from 2.0.0-beta6 to 2.1.0-alpha5

### PR DESCRIPTION
**Pull request by suheb**
Signed-off-by: Suhaib Khan <suheb.work@gmail.com>

### CODE REVIEW

**Comment by the-dagger** [comment]
@suheb I don't know, but should we force everyone to use the alpha plugin?
IMO we should hold back until the stable version is out.
Cheers.

**Comment by championswimmer** [comment]
Let's not use alpha as long as things build with the existing version.

**Comment by opticod** [comment]
Today gradle stable plugin version 2.0.0 is released , can be switch to stable version?

**Comment by mananwason** [comment]
Yes @opticod. Changed it in #331. Closing this @suheb @championswimmer

**Pull request closed without merging**
