### PR TITLE
chore: add NavExtension functions

### LINKED ISSUE #1701: Make NavExtensions for navigating
**Describe the chore**
After creating the bundle . Always `findController().` and then `navigateTo` is being written

we can create the extension function for this `navigateWithBundle()`
change code from this 
```
 TicketsFragmentArgs(safeArgs.eventId, currency)
            .toBundle()
            .also { bundle ->
                findNavController(rootView).navigate(R.id.ticketsFragment, bundle, getAnimSlide())
            }

```
to this

```
  TicketsFragmentArgs(safeArgs.eventId, currency)
            .toBundle()
            .naviagetwithBundleTo(rootView,R.id.ticketsFragment)
```

**Would you like to work on the issue?**

- [X] Yes

### PR DESCRIPTION
**Pull request by theLimitBreaker**
Fixes #1701 

Changes: 
add NavExtension functions

### CODE REVIEW

**Comment by theLimitBreaker** [comment]
@liveHarshit  @nikit19  please review

**Comment by iamareebjamal** [comment]
No need, we should be using Actions instead

**Comment by theLimitBreaker** [comment]
Ok I will be closing this

**Comment by theLimitBreaker** [comment]
Ok I will be closing this

**Pull request closed without merging**
