### PR TITLE
fix: Replace register button with progress bar when clicked.

### LINKED ISSUE #866: Replace register button with progress bar on submitting in Attendee Details.
**Describe the bug**

Progress Bar should come in place of Register Button in Attendee Details instead of below it.

**To Reproduce**

1. Go to the Attendee Details.
2. After filling out attendee details, click on the register button.

**Expected behavior**

Progress Bar should come in place of register button on clicking it.

**Screenshots**

terms_checkbox

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version| Android Pie 9.0.0 |

**Additional context**

@iamareebjamal @nikit19 Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by angmas1**
Fixes #866 

Changes: Replaced register button with progress bar when clicked.

Screenshots for the change:
ezgif com-video-to-gif

### CODE REVIEW

**Comment by angmas1** [comment]
I think it prevents user from spamming the button and sending multiple requests. We can also disable the button when it's clicked, but I think this looks better and also provides better location for progress bar.

**Comment by liveHarshit** [comment]
> I think it prevents user from spamming the button and sending multiple requests. We can also disable the button when it's clicked, but I think this looks better and also provides better location for progress bar.

Then disable the button while progress and change its color to something dull.

**Comment by angmas1** [comment]
> > I think it prevents user from spamming the button and sending multiple requests. We can also disable the button when it's clicked, but I think this looks better and also provides better location for progress bar.
> 
> Then disable the button while progress and change its color to something dull.
Should I remove the progress bar entirely then?

**Comment by liveHarshit** [comment]
https://developer.android.com/reference/android/graphics/drawable/AnimationDrawable

**Comment by angmas1** [comment]
ezgif com-video-to-gif

**Comment by angmas1** [comment]
@iamareebjamal @nikit19 Please review.

**Comment by angmas1** [comment]
@iamareebjamal @nikit19 please review.

**Pull request merged**
