### PR TITLE
Some Data Layer Test Added

### PR DESCRIPTION
**Pull request by opticod**
Some Date Layer Test Added #171 

- Session Insert Test

- Event Insert Test

- Microlocation Insert Test

### CODE REVIEW

**Comment by mananwason** [comment]
@opticod We want to create a full testing environment where we start by mocking an api using something like mockito and then add the data in the database and test the correctness there. These tests are really of no significance alone. Let me know if you'd like to work on this. I am closing this PR for now

**Comment by opticod** [comment]
@mananwason , If you read the discussion in #171 , creativepsyco have mentioned that he had added event test insertion , and he wants to add the remaining ones(deletion ,data correctness, etc) . He even encouraged :  ```the idea is to test as much database manager, helper code as possible,``` .

In this PR, I have completed the event test and added session and microlocation test. 

I can assure you that I will be adding more data layer test further, but this tests are also useful ones.

**Comment by championswimmer** [comment]
It'd be good to move these to unit tests (not instrumentation tests) using
something like Robolectric.

These are not dependent on Android per se, but on the sqlite driver. Having
the ability to test on local JVM will make these much faster, and part of
master branch's test suite.

(currently instrumentation tests are done only on stable branch)

**Comment by opticod** [comment]
Thank you, I will definitely learn and will implement them as suggested by you.

**Comment by the-dagger** [comment]
@opticod do you want to work on this together?
I too had to practice writing Unit Tests.
Cheers.

**Comment by opticod** [comment]
@the-dagger ,no - problem

**Comment by the-dagger** [comment]
Great, just let me know on gitter or here when you are planning to start.
Cheers.

**Comment by championswimmer** [comment]
Here is a example repo with tests
https://github.com/championswimmer/Android-Tests-Example

Here's how you can add a unit test (it is in the src/test folder, instead
of src/androidTest)
https://github.com/championswimmer/Android-Tests-Example/commit/4026467e82aa163bcfc6d84853308d7b18a42038

This is how to add support to unit tests (which is already done here)
https://github.com/championswimmer/Android-Tests-Example/commit/3a76a348d0692cc3c4b1fbcf2b560039d94f798d

**Comment by championswimmer** [comment]
Also here is how you can add DB tests using Robolectric
https://github.com/championswimmer/ReFuel/commit/11ae799a6a7cc9e9d070d5a298e1405eb8845e16

**Comment by the-dagger** [comment]
Thanks,  looks helpful. 
Will start working on this today after college. 
Cheers.

**Comment by opticod** [comment]
I have added some of them in #330 ,

**Pull request closed without merging**
