### PR TITLE
feat: Add Event FAQs

### LINKED ISSUE #1619: Add FAQ Section
**Describe the feature you'd like**
There Should be Section which shows the list of all FAQs related to that event

**Would you like to work on the issue?**
- [x] Yes

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Fixes #1619 

Changes: Added Event Faq's in About Event Fragment

Screenshots for the change:
screenshot-1555880744324
screenshot-1555881031765

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
This api is not yet merged to prod server so waiting for that otherwise it is complete

**Comment by iamareebjamal** [comment]
You don't use prod API, you use dev API

**Comment by aggarwalpulkit596** [comment]
I'm using prod server for testing

**Comment by aggarwalpulkit596** [comment]
@nikit19 review now

**Comment by iamareebjamal** [comment]
> I'm using prod server for testing

You shouldn't

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal okay I'll keep that in mind for future PR's

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal review

**Comment by iamareebjamal** [comment]
There should be an icon in the action bar which should open the FAQ fragment

**Comment by aggarwalpulkit596** [comment]
An entirely new fragment for faq ? Currently I'm showing them about event fargment

**Comment by iamareebjamal** [comment]
Yeah, new fragment

**Comment by aggarwalpulkit596** [comment]
@nikit19 @iamareebjamal updated

**Comment by iamareebjamal** [comment]
Text in action bar is fine. Remove the text in Fragment

**Comment by aggarwalpulkit596** [comment]
@liveHarshit review

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal updated

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal anything left out?

**Pull request merged**
