### PR TITLE
fix: Sign Up not working

### LINKED ISSUE #1870: Authentication fragments e-mail validation not working.
**Describe the bug**

In the main sign up page even if entering correct email address, the validator is throwing error stating invalid email address. 
**To Reproduce**

    1.Go to signup.
    2.Enter correct email ID.
    3.Next complete Signup page.
    4.Enter correct email ID.
    5.It will not be accepted.

**Expected behavior**

Form should proceed after correct validation. 

**Screenshots**
Testing

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #1870 

- According to the server implementation, password length should be 8 characters.

### CODE REVIEW

**Comment by ShridharGoel** [comment]
Shouldn't the error message be changed since it specifically says that the email is invalid while error 422 can be for other reasons too?

**Comment by liveHarshit** [comment]
> Shouldn't the error message be changed since it specifically says that the email is invalid while error 422 can be for other reasons too?

Yes. @nikit19 Where can I find docs about these error messages, because these are not in the server docs?

**Comment by anhanh11001** [comment]
So what was the reason for sign up not working properly (just because of short password?)

**Comment by vartult** [comment]
> So what was the reason for sign up not working properly (just because of short password?)

Yes the required minimum length for password is 8.

**Pull request merged**
