### PR TITLE
feat: Enlarge QR code and increase brightness on click

### LINKED ISSUE #1215: Enlarge QR code and increase brightness on clicking
**Describe the feature you'd like**
Feature to enlarge QR code and increase device's brightness when the QR code in order details is clicked.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1215 

Changes: 

Now, clicking on the QR code in order details would open a new fragment with the QR code in a larger size and increased phone brightness.

GIF for the change:

ezgif com-video-to-gif 55

### CODE REVIEW

**Comment by angmas1** [comment]
Use safe-args instead of bundles and try not to use !!

**Comment by liveHarshit** [comment]
Why is it require to enlarge the QR code?

**Comment by ShridharGoel** [comment]
For ease in scanning

**Comment by ShridharGoel** [comment]
I was experiencing this issue while trying to use safe args with bitmap.



Can anyone help on this?

**Comment by liveHarshit** [comment]
Any updates?

**Comment by aggarwalpulkit596** [comment]
@liveHarshit can i work on this

**Comment by ShridharGoel** [comment]
I'm a little busy with exams coming up, feel free to take this @aggarwalpulkit596

**Pull request closed without merging**
