### PR TITLE
Double press back to exit app issue has been resolved

### PR DESCRIPTION
**Pull request by Danki567**
Changelog:
-added functionality
-added toast to prompt user
-translated into all languages

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@Danki567 Can you close the old issue and follow the recommendations of the codacy-bot?
[Here](https://github.com/fossasia/open-event-android#codestyle) it is written that I shall reject your pull-request just because of style. Seems a bit off to me but you can open an issue if this does not feel right and I will add some argumentation ;)
What do you think?

**Comment by Danki567** [comment]
I did the proper styling, is there anything else that I need to fix.

**Comment by niccokunzmann** [comment]
Cool! Now, there is a build error, see the red cross with the travis haed next to it. This is the automated testing. I just clicked the link and a line: https://travis-ci.org/fossasia/open-event-android/builds/181203021#L2071

**Comment by niccokunzmann** [comment]
I would merge but since I am new to the project, I will notify the maintainers first to know if it is okay to merge code that fails on travis. List of maintainers: https://github.com/fossasia/open-event-android#maintainers

**Comment by Danki567** [comment]
ok thank you. to fix all you need to do is comment out 2 lines in the gradle. Should I comment them out

**Comment by niccokunzmann** [comment]
Oh, I just saw it: https://github.com/fossasia/open-event-android#branch-policy
They will not accept code that make travis red. I believe, there is some more work to be done.
I can understand if you are frustrated now, since you put in a lot of effort already.
But: be assured, you can ask for help. I am going to bed now, so I can not really help you now but I will be back tomorrow. 

Where you can get help: 

- the [FOSSASIA slack](http://fossasia-slack.herokuapp.com/), in the #gci channel
- ask the maintainers/last active contributors

I really appreciate your contribution. I would not be able to have done it so fast. I am a total newbie to this project but maybe I can help you anyway somehow :)

**Comment by niccokunzmann** [comment]
Oh, yes, you can do it and push.

**Comment by Danki567** [comment]
ok thanks. Can I get a time extension, I will not have enough time

**Comment by niccokunzmann** [comment]
By the way, in the gci16 FOSSASIA website, I saw that some people do not like merging a lot of commits. You can check out "squashing" git commits, so they are only one commit. Maybe they like it here, too.

**Comment by niccokunzmann** [comment]
Can you post the link for the task? I was reviewing so many tasks, I can not find it fast.

**Comment by Danki567** [comment]
https://codein.withgoogle.com/dashboard/task-instances/4557633801420800/?sp-page=2

**Comment by niccokunzmann** [comment]
Done! 5 days left. Is this enough? Just write if you need another 3 days.

**Comment by Danki567** [comment]
if that doesn't work try this https://codein.withgoogle.com/tasks/?sp-search=OPEN%20EVENT%20ANDROID:%20FIX%20ONE%20ISSUE%20IN%20EVENT%20ANDROID%20APP

**Comment by Danki567** [comment]
ok thanks

**Comment by free4murad** [comment]
@Danki567 
This issue was reported by me in issue no #794 
I have also made PR #794 for this.

**Comment by the-dagger** [comment]
@free4murad Thanks for bringing this to notice.

**Comment by niccokunzmann** [comment]
@the-dagger Why do you close this?

**Pull request closed without merging**
