### PR TITLE
fix: display cached images using picasso

### LINKED ISSUE #1326: Displaying cached images using Picasso
**Actual Behaviour**

Earlier in my issue i used Picasso to display cached images in SponserFragment. Extending that to all the parts having images.

**Expected Behaviour**

Display cached images when offline.

**Would you like to work on the issue?**

yes.

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1326 

Changes: 

Now cached images are displayed in offline mode using picasso.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
The `isActiveInternetPresent` function will block the UI and cause lag. It's better to use `isActiveInternetPresentObservable`

**Comment by arp95** [comment]
@iamareebjamal 
changed!

**Comment by arp95** [comment]
@the-dagger 
please review!

**Comment by the-dagger** [comment]
Can you please resolve the conflicts?

**Comment by arp95** [comment]
@the-dagger 
sorry didnt have a look till now.
Changing it!

**Comment by arp95** [comment]
@the-dagger 
have resolved conflicts.
Please review!

**Comment by iamareebjamal** [comment]
Does #1422 handle every case from this commit @arp95 ? 
Maybe @Shailesh351 and you can work together on whichever solution is better?

**Comment by Shailesh351** [comment]
@arp95 @iamareebjamal NetworkPolicy is used to load image from memory and cache only by not making network call for image. But picasso by default take cares of it. Picasso first try to load from memory then cache if it is not found then it makes request if internet is active. So i think simply loading using picasso will be enough.

**Comment by betterclever** [comment]
@Shailesh351 http://stackoverflow.com/questions/23978828/how-do-i-use-disk-caching-in-picasso 
Edit#2 of first answer suggests that Picasso doesn't load when we don't apply the Network Policy to be offline.

**Comment by betterclever** [comment]
@arp95 @Shailesh351 Can you both provide APKs of your respective implementations on your respective Pull Requests. That would make testing easy.

**Comment by the-dagger** [comment]
I'm closing this and #1422 
Maybe you two can work together to implement a better solution for this.

**Pull request closed without merging**
