### PR TITLE
feat: display profile menu options like preferences in fragment

### PR DESCRIPTION
**Pull request by addiegupta**
Fixes: #1439

Changes:
 * Menu options have been removed from ProfileFragment and instead displayed like Preferences within the fragment
to utilise the waste empty space. Layout has been improved to support this.

 * ic_baseline_event_black.xml has been refactored to ic_baseline_event_grey.xml as the it constituted of the grey color

 * 2 drawable vector asset have been added for using in the layout
 *  `showDialog` has been refactored to `showLogoutDialog` for more detail

Screenshots for the change:

Old Fragment

New Fragment

PR Profile revamp

### CODE REVIEW

**Comment by addiegupta** [comment]
@liveHarshit please review

**Comment by liveHarshit** [comment]
Why all menu items in the profile section?
 The back button is not displayed in settings fragment.

**Comment by addiegupta** [comment]
> Why all menu items in the profile section?

Currently the Profile Fragment looks very empty and even Eventbrite has options listed like this you can checkout the screenshot in Issue #1439 


> The back button is not displayed in settings fragment.

I didnt understand what you meant

**Comment by liveHarshit** [comment]
Settings and Tickets options are not supposed to appear in profile.

**Comment by liveHarshit** [comment]
> I didnt understand what you meant

Back button at top.

**Comment by addiegupta** [comment]
> > I didnt understand what you meant
> 
> Back button at top.

It is there in the GIF, you might have missed it

**Comment by addiegupta** [comment]
> Settings and Tickets options are not supposed to appear in profile.

We are following eventbrite right? And @iamareebjamal had assigned a label to this issue so i think it was approved

**Pull request merged**
