### PR TITLE
Fixes 1711 : Unknown pattern character 'X' error in ISO8601Date

### LINKED ISSUE #1711: Unknown pattern character 'X' error in ISO8601Date
**Actual Behaviour**

Initially, the app is crashing after the downloading of data from the server. Any subsequent run of the app, the app is crashing on initialisation itself.

**Expected Behaviour**

The app should should run fine with the specified date format.

**LogCat for the issue**

screenshot from 2017-06-15 21-55-36

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 6](https://github.com/fossasia/open-event-android/milestone/29)

### PR DESCRIPTION
**Pull request by rohanagarwal94**
Fixes #1711

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
@iamareebjamal @arp95 @mahikaw @shreyasnbhat @Shailesh351 @heysadboy please review.

**Comment by iamareebjamal** [comment]
Fix the tests please

**Comment by iamareebjamal** [comment]
@rohanagarwal94 This won't be needed when #1700 is merged

**Comment by rohanagarwal94** [comment]
@iamareebjamal closing this then.

**Pull request closed without merging**
