### PR TITLE
Improved splash screen

### PR DESCRIPTION
**Pull request by utkarshnath**
Solved #868

### CODE REVIEW

**Comment by mananwason** [comment]
Could you add a screenshot or better yet a gif for the changes? Thanks

**Comment by utkarshnath** [comment]
@mananwason Done
**Now we don't have blank screen in between splash screen and main activity**
www gifcreator me_rbwm29

**Comment by mananwason** [comment]
@utkarshnath How have you handled the cases when the download takes a long time? Is there a timeout? Also what about if the user doesn't want to download the data and instead wants offline json content that is packaged into the app?

**Comment by utkarshnath** [comment]
@mananwason I am waiting only till the views of the main Activity is constructed(so that we don't get a blank screen) and not till the data gets downloaded. So as soon as view is constructed we move on to main activity and downloading starts and we can see the progress bar if the internet is present otherwise we receive a dialog box for switching on the internet.

**Pull request merged**
