### PR TITLE
fix: Data retention on orientation change for all activities.

### LINKED ISSUE #1016: User Details and Image is lost in screen rotation
**Describe the bug**
When the user edits his/her profile, then the entered data and loaded image is not retained when the screen is rotated.

**To Reproduce**
Profile -> Edit -> Enter details, select an image and rotate the screen.

**Expected behavior**
Entered data and image should retain

**Screenshots**
videotogif_2019 02 03_17 12 19

**Smartphone Info:**
Redmi Note5 pro 8.1 Oreo

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by angmas1**
Fixes #1016 #1005 #967 #1004 #652 #1048 

Changes: Changed AndroidManifest.xml to have android:configChanges="orientation|screenSize" which prevents call onCreate when orientation is changed.

Screenshots for the change:
ezgif com-video-to-gif
ezgif com-video-to-gif 1

### CODE REVIEW

**Comment by angmas1** [comment]
> Wrong
Why? Please elaborate.
This solves all the problems.

**Comment by iamareebjamal** [comment]
Try to change the landscape layout of the activity and see if it works

**Comment by angmas1** [comment]
Specify one or more configuration changes that the activity will handle itself. If not specified, the activity will be restarted if any of these configuration changes happen in the system. Otherwise, the activity will remain running and its {@link android.app.Activity#onConfigurationChanged Activity.onConfigurationChanged} method called with the new configuration.

Description of this property in Android Studio.

According to this orientation change will be ignored only if it's not specified in the activity.

**Comment by angmas1** [comment]
I checked the code but couldn't find any instance where specific layout was present for landscape mode. Please let me know if you find any. All fragments that I checked worked as they used to before.

**Comment by shiv07tiwari** [comment]
@angmas1 A lot of people are already working on this issue talking up different activities.
#1016
#967

**Comment by iamareebjamal** [comment]
I asked you to try to change the orientation layout of the fragment. The answer is you can't

The correct solution is to correctly use ViewModels and LiveData

**Pull request closed without merging**
