### PR TITLE
Small UI improvements in speaker and sponsor sections.

### PR DESCRIPTION
**Pull request by suheb**
Also updating splash screen image.

Screenshots:

Before:
screenshot_2016-02-04-01-44-53
After:
screenshot_2016-02-04-01-43-41

Before:
screenshot_2016-02-03-23-12-11
After:
screenshot_2016-02-03-23-26-04

Signed-off-by: Suhaib Khan <suheb.work@gmail.com>

### CODE REVIEW

**Comment by mananwason** [comment]
@suheb According to material design guidelines,cards shouldn't be used with similar content. Please remove the changes in sponsor layout, You can just introduce a margin there. That would do the trick. Cheers!

**Comment by suheb** [comment]
@mananwason I used cardview just to get a drop shadow which cleanly separates the sponsor logos and looks pretty cool ( adding only the margin doesn't work because of the white color in both logos and background). 
The other method to add drop shadow is somewhat cumbersome, but I could do that if we absolutely don't want cards here.

**Comment by suheb** [comment]
@mananwason Now that I think about it, you're right, the cards are kind of distracting.
See my latest commit. I have added a divider to separate the logos.

**Comment by creativepsyco** [comment]
i believe @mananwason is also fixing this. please check with him on design.

**Comment by mananwason** [comment]
@suheb I have created a PR #190. Please see that.

**Comment by creativepsyco** [comment]
failed build.

**Comment by suheb** [comment]
@creativepsyco Why this build is failing? I just added a margin after all.

**Comment by suheb** [comment]
Okay so I saw the build log, it's failing because of this error:
:app:processFdroidDebugResources/home/travis/build/fossasia/open-event-android/app/src/main/res/layout/activity_splash.xml:11:22-43: AAPT: No resource found that matches the given name (at 'src' with value '@drawable/ic_launcher').
But I don't understand as ic_launcher is present in drawable.

**Comment by creativepsyco** [comment]
you should rebase with master again.

**Comment by suheb** [comment]
@creativepsyco Rebasing with master created so many commits in this pull request. Would you be able to merge this or should I open another pull request?

**Comment by creativepsyco** [comment]
thats because you merged with parent fork previously. You branch off from master again, cherry pick your commits and force push again check this out: https://www.youtube.com/watch?v=oFYyTZwMyAg

**Comment by suheb** [comment]
@creativepsyco I think we are good to go here.

**Comment by mananwason** [comment]
@suheb please remove the merge commit.

**Comment by suheb** [comment]
@mananwason Done

**Comment by mananwason** [comment]
Looks fine @suheb. Merging.

**Pull request merged**
