### PR TITLE
fix: Added Retry button

### PR DESCRIPTION
**Pull request by somenath1435**
Fixes #1175 

Changes: Added button instead of text(user can click on button)
AndroidX button is added.

Screenshots for the change:
Before:-
whatsapp image 2019-02-24 at 4 22 19 am

After:-
whatsapp image 2019-02-24 at 9 19 48 pm

### CODE REVIEW

**Comment by somenath1435** [comment]
@iamareebjamal I believe this button looks better than flat button.
Also, button shows that user can click on it, normal text may not feel like to be clicked by the user.

**Comment by somenath1435** [comment]
@nitik19
Actually I added the button so that user can click on it.
User may not tap on plain text.

**Comment by somenath1435** [comment]
@nikit19 I added the button so that user can click on it.
User may not click on plain text

**Comment by somenath1435** [comment]
@iamareebjamal Shall I make some additional changes or shall I close this issue?

**Comment by iamareebjamal** [comment]
Close

**Pull request closed without merging**
