### PR TITLE
added error handling in retrofit 2

### PR DESCRIPTION
**Pull request by mananwason**
@the-dagger Please review and merge

### CODE REVIEW

**Comment by mananwason** [comment]
fixes #426

**Comment by the-dagger** [comment]
@mananwason codacy checks suggest some fixes. 
Could you update them? 
Cheers.

**Comment by mananwason** [comment]
@the-dagger Please check now. Codacy issues have been resolved

**Comment by the-dagger** [comment]
Looks good, merging

**Pull request merged**
