### PR TITLE
feat: Add track for event

### PR DESCRIPTION
**Pull request by anhanh11001**
Detail:
- Delete Scope
- Add track to session item view and session fragment
- Remove wildcard imports

Fixes:: #1694 

**Screenshots**

### CODE REVIEW

**Comment by mariobehling** [comment]
Travis is failing. Please fix it.

**Comment by anhanh11001** [comment]
updated

**Comment by iamareebjamal** [comment]
Color code is not meant to be shown in that manner. Make it card header color

**Comment by anhanh11001** [comment]
@iamareebjamal updated

**Comment by iamareebjamal** [comment]
Great work

**Pull request merged**
