### PR TITLE
Fix: App crashing in bookmarks fragment.

### LINKED ISSUE #1202: App Crashing
**Actual Behaviour**

App is crashing.

**Expected Behaviour**

It should not crash.

**Steps to reproduce it**

Open bookmarks fragment. Click on search icon on top and write text to search something. Without closing the search bar, swipe right to open navigation drawer and then open any other fragment.

**LogCat for the issue**
```
FATAL EXCEPTION: main
Process: org.fossasia.openevent, PID: 22867
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.scrollToPosition(int)' on a null object reference
    at org.fossasia.openevent.fragments.BookmarksFragment.onQueryTextChange(BookmarksFragment.java:214)
    at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1237)
    at android.support.v7.widget.SearchView$12.onTextChanged(SearchView.java:1767)
    at android.widget.TextView.sendOnTextChanged(TextView.java:7998)
    at android.widget.TextView.setText(TextView.java:4355)
    at android.widget.TextView.setText(TextView.java:4209)
    at android.widget.EditText.setText(EditText.java:84)
    at android.widget.TextView.setText(TextView.java:4184)
    at android.support.v7.widget.SearchView.setQuery(SearchView.java:612)
    at android.support.v7.widget.SearchView.onActionViewCollapsed(SearchView.java:1334)
    at android.support.v7.widget.Toolbar$ExpandedActionViewMenuPresenter.collapseItemActionView(Toolbar.java:2388)
    at android.support.v7.view.menu.MenuBuilder.collapseItemActionView(MenuBuilder.java:1366)
    at android.support.v7.view.menu.MenuBuilder.clear(MenuBuilder.java:594)
    at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:453)
    at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:603)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:746)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5443)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by chiragw15**
Fixes #1202 

Changes: App not crashing now.

### CODE REVIEW

**Comment by harshitagupta30** [comment]
@chiragw15 Can you please update your commit message according to [guidelines](https://github.com/fossasia/open-event-android/blob/development/docs/commitstyle.md) :+1:

**Comment by chiragw15** [comment]
@harshitagupta30 Sorry, susi habits. Is it fine now?

**Comment by harshitagupta30** [comment]
@chiragw15 No issues! Can you remove Fixes#1202 I guess its not required. Thanks :+1:

**Comment by chiragw15** [comment]
@harshitagupta30 Don't we need to refer issue number in the commit message. Aren't we following "Single commit per pull request" policy. Plus, Its mentioned in the docs too.

**Comment by harshitagupta30** [comment]
@chiragw15 When you're writing Fixes in the subject it itself points to that, no need to write in commit message.

**Comment by mananwason** [comment]
LGTM merging

**Pull request merged**
