### PR TITLE
Language preferences in user settings

### PR DESCRIPTION
**Pull request by rohanagarwal94**
#828 is fixed. @the-dagger and @mariobehling please review.
screenshot_2016-12-11-20-04-22-020_org fossasia openevent

### CODE REVIEW

**Comment by the-dagger** [comment]
Rather than setting it to `en`, could you show the actual language to the user?
I personally feel like displaying `English` makes more sense than displaying `en`

**Comment by rohanagarwal94** [comment]
@the-dagger the default language comes from the system and might vary for custom android devices. Therefore cant really do string mapping too.

**Comment by the-dagger** [comment]
You won't need to map it.
Have a look over here.
[http://stackoverflow.com/a/23168383/5471095](http://stackoverflow.com/a/23168383/5471095)

**Comment by rohanagarwal94** [comment]
@the-dagger thanks for helping out. Made the necessary changes.

**Pull request merged**
