### PR TITLE
fix: Display valid information about sessions, speakers, call for speakers

### PR DESCRIPTION
**Pull request by anhanh11001**
Display only:
- featured speakers
- accepted sessions
- public call for speaker

Fixes: #1897

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Open an issue on server. It should show only accepted things by default

**Comment by anhanh11001** [comment]
@iamareebjamal But then I think the orga app can't receive the full list of pending speakers/sessions?

**Comment by iamareebjamal** [comment]
Onbviously, an organizer can and will be able to see all. Attendee shouldn't be able to

**Comment by anhanh11001** [comment]
oh never mind, I was overthinking of an another problem. I'm opening an issue now

**Comment by anhanh11001** [comment]
As the session and speakers call are handled by the server, I only made the filter for speakers

**Comment by iamareebjamal** [comment]
It'd be better if there's no featured speaker, fall back to all speakers

**Pull request merged**
