### PR TITLE
Merge branch 'development'

### PR DESCRIPTION
**Pull request by nikit19**

### CODE REVIEW

**Comment by nikit19** [comment]
@iamareebjamal Please review

**Comment by iamareebjamal** [comment]
To be merged after README is fixed

**Comment by nikit19** [comment]
@iamareebjamal please review. and how should I tag the commit ? Through github release ?

**Comment by iamareebjamal** [comment]
@nikit19 No, through git CLI

Also, the master dev branch apk PR is still not complete so we need to wait for that. Till that, you should install and check the F-Droid version and if it is working correctly

**Comment by iamareebjamal** [comment]
Tag is to be added when the merge is complete

**Pull request merged**
