### PR TITLE
restructured repo to separate app and apk generator

### PR DESCRIPTION
**Pull request by mananwason**

### CODE REVIEW

**Comment by mananwason** [comment]
@mariobehling @the-dagger this is the restructure we talked about. Please check and merge

**Comment by the-dagger** [comment]
Looks good to me @mananwason :+1: 
P.S. Before you merge this, just create an issue for the same.
Cheers.

**Comment by mananwason** [comment]
fixes #376

**Comment by mananwason** [comment]
Merging this @the-dagger @mariobehling

**Pull request merged**
