### PR TITLE
feat: Add delete user photo feature

### PR DESCRIPTION
**Pull request by anhanh11001**
Detail:
- Update user photo by default image (encoded)

Fixes: #1017

### CODE REVIEW

**Comment by iamareebjamal** [comment]
But it won't be cleared on server?

**Comment by anhanh11001** [comment]
@iamareebjamal You mean the previous user profile image? I think the server doesn't have the option to delete an image, only to upload it. By deleting user photo in issue #1017, I think it means just setting the profile image to a default image

**Comment by iamareebjamal** [comment]
You can set it to null on the server

**Comment by anhanh11001** [comment]
@iamareebjamal I think when sending a null image URL to the server, the current way server handles it is to ignore it and retain the previous profile image URL. I'm working with @uds5501 on this.

**Comment by iamareebjamal** [comment]
@anhanh11001 Any update about the QR change you did. Is it compatible with the orga app?

**Comment by anhanh11001** [comment]
Oh sorry for forgetting to finish it, I'm doing it now. Previously, I did take a look at it but the ScanActivity in orga app was blocked so I was confused but I forgot to ask you about that. I'll take a look again now and update to you later today.

**Comment by anhanh11001** [comment]
@iamareebjamal I have checked it, it is handled correctly with "orderIdentifier-attendeeId"
save

**Comment by ShridharGoel** [comment]
> Oh sorry for forgetting to finish it, I'm doing it now. Previously, I did take a look at it but the ScanActivity in orga app was blocked so I was confused but I forgot to ask you about that. I'll take a look again now and update to you later today.

Scanning is enabled in the Play Store build variant.

**Pull request merged**
