### PR TITLE
Fix: Refresh flow bug in Track Fragment

### PR DESCRIPTION
**Pull request by opticod**
Fix: Refresh flow bug in Track Fragment

Resolves: #756

### CODE REVIEW

**Comment by opticod** [comment]
Still got the merge conflict after rebasing with the current development branch. Can you please resolve the merge conflict?

**Comment by the-dagger** [comment]
@opticod I won't be able to resolve the merge conflict as I don't have write access to your branch. 
Also if rebased properly, there shouldn't be any merge conflict as such.

**Comment by opticod** [comment]
Resolved the merge conflict.

**Comment by mariobehling** [comment]
Please check travis is not building.

**Comment by opticod** [comment]
This time travis passed. Can you please help me out to pass the ```codecov/test```?

**Comment by mariobehling** [comment]
Yes, I restarted the test as there are sometimes issues. Codecov requires additional work, which can be solved in a separate issue. Thank you.

**Pull request merged**
