### PR TITLE
Revamp Login Fragment

### PR DESCRIPTION
**Pull request by namanpreetsingh**
Login Fragment looks like this now ---
image
image
UI elements in Forgot Password were not well placed.

### CODE REVIEW

**Comment by dreadpool2** [comment]
This revamped version is not similar to EventBrite. I think it was quite fine before

**Comment by dreadpool2** [comment]
@namanpreetsingh You did not raise an issue for this PR

**Comment by dreadpool2** [comment]
@namanpreetsingh Yeah, but the check is present in the top most right corner in the latest version.
42723656_232939917580949_226431762471845888_n

**Comment by namanpreetsingh** [comment]
@dreadpool2  But it doesn't quite look like it in my device. Why is it so?
screenshot_2018-09-29-22-26-29-426_com eventyay attendee

**Pull request closed without merging**
