### PR TITLE
chore: Release v0.2.1

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@liveHarshit @anhanh11001 Please ensure that 

1. Upgrade from v0.2.0 to v0.2.1 is possible
2. Version Code and Name are up to date (0.2.1 and code incremented)
3. There are no major bugs in the release

**Comment by iamareebjamal** [comment]
Moving forward, we'll adopt fortnightly release with all issues having proper milestones. We'll discuss the process soon

**Comment by liveHarshit** [comment]
> @liveHarshit @anhanh11001 Please ensure that
> 
> 1. Upgrade from v0.2.0 to v0.2.1 is possible
> 2. Version Code and Name are up to date (0.2.1 and code incremented)
> 3. There are no major bugs in the release

I will ensure by tonight.

**Comment by anhanh11001** [comment]
I'll do it soon today

**Comment by anhanh11001** [comment]
I found an issue #1715 and it seems like we have to update the database schema as well as not to get the bug in the last update

**Comment by anhanh11001** [comment]
@iamareebjamal In the last release, the database table version is 2. Currently, the database table version in the development branch is 4, and the database scheme file (4.json is not committed). Should I upload the 4.json file or should I change the database version back to 3 and send the 3.json file?

**Comment by iamareebjamal** [comment]
Upload 4.json

**Comment by liveHarshit** [comment]
@iamareebjamal Should I put a PR to bump version name and code for this release?

**Comment by liveHarshit** [comment]
> 3\. There are no major bugs in the release

#1719

**Comment by liveHarshit** [comment]
> 3\. There are no major bugs in the release

#1729 #1732 #1730

**Pull request merged**
