### PR TITLE
feat: Add ripple effect for RETRY

### LINKED ISSUE #1297: Add ripple effect on retry button
**Describe the feature you'd like**
Add ripple effect when clicking on RETRY button (internet fail) on EventsFragment

**Screenshots**

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by anhanh11001**
Fixes #1297 

Screenshots for the change:
54369268-2254940751411753-8953746763244634112-n

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Use borderless buttons

**Comment by anhanh11001** [comment]
@iamareebjamal I have changed that

**Comment by iamareebjamal** [comment]
Why not using a borderless button

**Comment by anhanh11001** [comment]
@iamareebjamal sorry I misunderstood your point in the beginning, I have changed that into a borderless button

**Pull request merged**
