### PR TITLE
feat: changed app icon

### LINKED ISSUE #434: Create an icon for the app
Working on it :+1:

### PR DESCRIPTION
**Pull request by simarsingh24**
fixes #434

### CODE REVIEW

**Comment by iamareebjamal** [comment]
We're not showing adaptive icons right now, so use the traditional way

**Comment by simarsingh24** [comment]
@iamareebjamal i am using shape type as vertical

**Comment by iamareebjamal** [comment]
But in the PR you have still used other shapes

**Comment by simarsingh24** [comment]
@iamareebjamal I have used AS tool to import the image assest as launcher and it asked for shape which i selected as vertical

**Comment by simarsingh24** [comment]
selected shape type as none

**Pull request merged**
