### PR TITLE
Exit on double back press implemented.

### PR DESCRIPTION
**Pull request by free4murad**
Solved issue #793

### CODE REVIEW

**Comment by mariobehling** [comment]
Great to see progress on this!

@free4murad Please check. Travis is failing.

**Comment by Danki567** [comment]
#793 Fixed by adding this into mainActivity
boolean exitDouble = false;

    @Override
    public void onBackPressed() {
        FragmentManager fragmentManager = getSupportFragmentManager();
        android.support.v4.app.Fragment fragment = fragmentManager.findFragmentByTag(FRAGMENT_TAG_TRACKS);
        if (drawerLayout.isDrawerOpen(GravityCompat.START)) {
            drawerLayout.closeDrawer(GravityCompat.START);
        } else if (fragment != null && fragment.isVisible()  &&  exitDouble) {
            super.onBackPressed();
        } else {
            exitDouble = true;
            Toast.makeText(this, R.string.double_press_exit, Toast.LENGTH_SHORT).show();
            fragmentManager.beginTransaction()
                    .replace(R.id.content_frame, new TracksFragment(), FRAGMENT_TAG_TRACKS).commit();
            if (getSupportActionBar() != null) {
                getSupportActionBar().setTitle(R.string.menu_tracks);
            }
            navigationView.setCheckedItem(R.id.nav_tracks);
        }
    }

**Comment by free4murad** [comment]
@the-dagger 
Will make a new PR.

**Comment by Danki567** [comment]
Why

**Comment by free4murad** [comment]
@Danki567 
I have to rebase my repo because Travis.yml was updated.

**Pull request closed without merging**
