### PR TITLE
Same date and time is displayed even when opening different events #970

### PR DESCRIPTION
**Pull request by ani27**
RESOLVED

### CODE REVIEW

**Comment by ani27** [comment]
@mananwason  Any reviews on this?

**Comment by the-dagger** [comment]
There seems to be conflicts in `SessionListAdapter.java`, can you please resolve it?

**Comment by ani27** [comment]
@the-dagger  I have resolved the conflicts. Please review.

**Comment by ani27** [comment]
@the-dagger  please review this PR?

**Pull request merged**
