### PR TITLE
Fixes #564

### LINKED ISSUE #564: Implement more useful map page, e.g. currently map does not show address of event location
* [x] As a first step add location info on map
* [x] Show a screenshot here what you plan to implement before making a PR

### PR DESCRIPTION
**Pull request by mananwason**
@the-dagger @mariobehling Please review and merge. This PR adds location markers to maps and fixes other implementation issues with maps.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a screenshot and check why codacy is currently not running.

**Comment by mananwason** [comment]
@mariobehling These are the screenshots for both Google maps variant as well as OpenStreetMaps variant. 
device-2016-08-12-162116
device-2016-08-12-214802

About codacy, I am not sure why it says that it was unable to analyse the commit whereas it has already done so and displayed the results https://www.codacy.com/app/harshithdwivedi/open-event-android/pullRequest?prid=315545

**Comment by mariobehling** [comment]
This still does not fix issue #564. Could you also please make it easy for everyone and provide the info which issue is related in the description? I am sad, that you still do not follow best practices at the end of GSoC.

**Comment by mariobehling** [comment]
The actual address and location info is still missing.

**Comment by mananwason** [comment]
@mariobehling I have added the information about the fixes to the description of this PR already. What more should I add, Can you please guide me? 
Also for the address, it's not provided by the api. I have already added the location name though.

**Comment by mananwason** [comment]
@mariobehling If the user clicks the red marker, the location name and navigation instructions are shown. Right now the location name in the sample is ```Singapore```
device-2016-08-12-222757

**Comment by rohanagarwal94** [comment]
@mananwason anything I could contribute to this thread? would you please provide the markers json so that i could complete the clustoring and show/hide markers on different levels.

**Comment by mananwason** [comment]
@rohanagarwal94 let's follow up on that issue.

**Comment by mariobehling** [comment]
Thank you, please open an issue, that the location information is not provided in the API in the orga server.

Please in future provide the issue number/link in the description itself to make it easy to follow up.

**Comment by mananwason** [comment]
Sure @mariobehling. Got it!

**Pull request merged**
