### PR TITLE
fix: resolved the memory leak in DayScheduleFragment

### LINKED ISSUE #1489: DayScheduleFragment leaked 109 KB
**Actual Behaviour**

After using the app for a while i get a notification as seen below for the information leakage.

**Expected Behaviour**

Adding appropriate permissions in the manifest file to avoid that.

**Steps to reproduce it**

1. Use the app for several minutes.
2. While doing so go to different items like tracks, location, schedule etc.
3. You will get a notification of information leaked.

**LogCat for the issue**

-

**Screenshots of the issue**

18361852_10211217388265000_881712396_o

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1489 

Changes: 

Actually the hashmap is causing the memory leak problem. Resolved it.

Screenshots for the change: 

-

### CODE REVIEW

**Comment by mahikaw** [comment]
@arp95 could you please review the issue again. I think it is still persisting.

**Comment by Shailesh351** [comment]
@arp95  memory leak not resolved yet.I am still getting memory leak in DayScheduleFragment. Please check it again.
Thanks

**Comment by arp95** [comment]
have an exam today. will have a look in the evening.

**Comment by Shailesh351** [comment]
Okay..
@arp95 always try to check is there is any bug after solving issue and implementing feature.

Filter is not working properly after this PR.

**Comment by mahikaw** [comment]
@arp95 have you had a chance to look at the issue? 

- the memory leaks are persistent

- the filter feature is not working properly after this.

**Comment by arp95** [comment]
@mahikaw 
yeah having a look.

@the-dagger 
actually the memory leak exists because of the hashmap in filter which i removed and another reason is the fragment list in the schedule viewpager adapter. As the fragments keep on being added a large heap is created which is reported by LeakCanary. One solution i found to this was using FragmentStatePagerAdapter but using this still makes leak prevalent. Any ideas?

**Pull request merged**
