### PR TITLE
fix: make event details UI same as before

### LINKED ISSUE #151: Event details UI has changed
ticket textview should of black color and the last divide line should look like the other divide lines
working on it
screenshot_20180618-013619

### PR DESCRIPTION
**Pull request by nikit19**
fixes #151 
screenshot_20180618-015758

### CODE REVIEW

**Comment by dreadpool2** [comment]
@nikit19 Could you please change the tickets UI text color to blue/black as well ?

**Comment by nikit19** [comment]
@dreadpool2 what? tickets textView is already in black

**Comment by dreadpool2** [comment]
I meant the green and pink ones ( the actual tickets )

**Comment by nikit19** [comment]
is that needed? Actually I am just reverting the extra changes you made in the last PR that got merged

**Comment by dreadpool2** [comment]
Yeah I saw that too :+1:  So do you think the colour scheme of tickets should remain the same ?

**Comment by nikit19** [comment]
green looks fine. The pink color looks odd but that it is our accent color.
So I think at a later stage when we will be working on the UI we can change the accent color .

**Pull request merged**
