### PR TITLE
Make application asynchronous using Rx  (for #1269)

### LINKED ISSUE #1269: Make DB interactions asynchronous using loaders or Rx
**Actual Behaviour**

UI is very jittery and lags on transitions from activity to activity due to heavy initialization on main thread and specifically in onCreate. 

**Expected Behaviour**

We could use Loaders or RxJava to make these tasks asynchronous. However our database doesn't change in real time and CursorLoaders are de-facto standard in Android for DB interactions, I think integration with Rx makes it very easy to scale the application in future and also makes it quite more testable using side effects. Using Rx also means we won't have to change our data model a lot, just wrap it around and we will be good. Almost all core db interactions reside in `DatabaseOperations.java`, even the internal handling of cursors, which will make implementing Loaders somewhat tedious than Rx
I think it will be a right step in improving the performance of the app.

**Would you like to work on the issue?**

Yes, I would like to work on the issue

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #1269 

Changes:
- Make database operations reactive

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Changes -

- Correct shared elements regarding the asynchronous loading of data in Session Detail view
- Make Session Adapter reactive

**Comment by iamareebjamal** [comment]
Please review @the-dagger

**Comment by arp95** [comment]
@iamareebjamal 
squash the commits!

**Comment by iamareebjamal** [comment]
@arp95 Done :+1:

**Comment by mariobehling** [comment]
As many PRs are getting merged, some have merge conflicts. Please help to resolve them here.

**Comment by iamareebjamal** [comment]
Done @mariobehling :smile:

**Pull request merged**
