### PR TITLE
fixes issue 788

### PR DESCRIPTION
**Pull request by arp95**

### CODE REVIEW

**Comment by the-dagger** [comment]
@arp95 it would be better if you can structure your pull requests in the same way as done in GitHub.com/fossasia/susi_android.
Pull Requests with blank message and no screenshots makes it hard for us to keep track.

**Comment by arp95** [comment]
@the-dagger will take this into account from now onwards.
what i did over here is add a fab on session detail activity which on a click takes me to the map activity.

14963524_10209567815826720_1752529871_o

**Comment by the-dagger** [comment]
Looks good. :+1:
Change the location drawable to be white in color so that it matches with the overall ui of the app.

**Comment by arp95** [comment]
@the-dagger have made the changes . please look into this .

15007797_10209568345999974_1649280488_o 1

**Pull request merged**
