### PR TITLE
feat: Added Shimmer to display Tickets

### LINKED ISSUE #1372: Use Shimmer to display Tickets
**Describe the feature you'd like**
Replace progressbar with shimmer to display tickets.
It is already used in events page.

**Screenshots**

aab

**Would you like to work on the issue?**

- [x] Yes

### PR DESCRIPTION
**Pull request by somenath1435**
Fixes #1372 

Changes: Added Shimmer to display Tickets.

Screenshots for the change:
zz

### CODE REVIEW

**Comment by haroldadmin** [comment]
Thank you for your contribution. If I may nitpick before reviewing this PR, I can see that you are re-using the search items placeholder layout for tickets as well. It would be great if you could create a new placeholder layout for tickets which looks similar to the `item_card_order.xml` layout for shimmering.

**Comment by liveHarshit** [comment]
Both layouts are different please create a new placeholder.

**Comment by somenath1435** [comment]
@liveHarshit I will update the PR tomorrow.

**Comment by somenath1435** [comment]
@liveHarshit Updated PR
xxa

**Comment by liveHarshit** [comment]
Resolve conflicts. And size for the first block should be half, same as size of date.

**Comment by somenath1435** [comment]
@liveHarshit see new looks:-
Screenshot_20190323-211234

**Comment by liveHarshit** [comment]
Looks good. Please resolve conflicts.

**Comment by somenath1435** [comment]
Resolved conflicts.
PR is ready in my opinion

**Pull request merged**
