### PR TITLE
Revert "APK size reduced." to fix #963

### LINKED ISSUE #963: App NOT working on Redmi Note 3
Before proceeding further , I would like to share my phone's features :- 

Model No. - Redmi Note 3
Android version - 6.0.1 MMB29M
MIUI version - MIUI Global 8.1 | Stable 8.1.10 (MHOMIDI)

The problem I'm facing -> I have installed the OpenEvent App but it's not working. Whenever I try to open the app, a message saying that the "Unfortunately, OpenEvent app has stopped" pops out. You can check the bug report right out !

whatsapp image 2017-01-05 at 16 51 40

whatsapp image 2017-01-05 at 16 50 57

### PR DESCRIPTION
**Pull request by mananwason**

### CODE REVIEW

**Comment by free4murad** [comment]
@mananwason
I tried running the code on following devices -

Moto G4 Plus, Android - 6.0.1
Samsung Galaxy J2, Android - 6.0.1
Moto E3 Power, Android - 6.0
Its working fine on these devices.

I have customised the proguard rules.
Also just to be sure I have kept all libraries that may use reflection.

**Comment by saketkumar95** [comment]
@mananwason It's working fine now. :+1: 
@free4murad I did checked on all the devices you mentioned here. It's not working. I don't know how it's working on your device.

**Comment by mananwason** [comment]
@free4murad I'm not sure why it's working on your devices because the proguard rules are not correctly configured.

**Comment by free4murad** [comment]
@mananwason
while debugging the app I saw these libraries in the logcat.
That's why I added them to the proguard rules.

Anyway I will work on it again and send a new PR

**Comment by saketkumar95** [comment]
@free4murad i was working on this issue. https://github.com/fossasia/open-event-android/issues/925 
Let me do this time. :)

**Pull request merged**
