### PR TITLE
Remove the GPlay badge

### PR DESCRIPTION
**Pull request by the-dagger**
I am temporarily removing the google play store badge as it isn't required as of now.

### CODE REVIEW

**Comment by mananwason** [comment]
@the-dagger This is not required. Instead of removing the badge, we should add a new apk that works with the new json

**Comment by the-dagger** [comment]
Agreed but lets keep this logo in master's readme.
What say?
Having it in devel readme isn't needed

**Comment by mananwason** [comment]
How does it matter? @the-dagger. As it is the default branch is development, so someone who comes to the repo should be able to see the app on the play store as well.

**Comment by the-dagger** [comment]
Ok, cool then. :+1:

**Comment by mananwason** [comment]
👍

**Pull request closed without merging**
