### PR TITLE
Fetch and package everything during app compilation

### LINKED ISSUE #585: Send notification to orga server if android app is generated
@mananwason @the-dagger  If Android App is generated please send a notification to orga server

I've created notification API:
http://open-event-dev.herokuapp.com//#!/notifications/post_user_notifications.

Code sample: 
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
"action": "AndroidApp is generated",
"message": "string",
"email": "rafal@wp.pl",
"title": "string"
}' 'http://open-event-dev.herokuapp.com/events/1/notifications'

### LINKED ISSUE #619: Fetch the data on server from API at the build time
As outlined in today's chat, we need to take care of the following things.
* [x] Fetch the JSON files from the API provided by the user.
* [x] Extract event name from event.json and use it as the app name
* [x] Extract the logo from event.json and use it as the app's icon.
* [x] Remove the App Name field from the web page.
* [ ] Copy the json files into the assets folder prior to app compilation

### LINKED ISSUE #643: Use default logo if not provided
The sample api that we are using to test our app [https://open-event-dev.herokuapp.com/api/v2/events/9](https://open-event-dev.herokuapp.com/api/v2/events/9) has its logo set to `""`.
So for such cases in which there is no logo provided by the organizer, we will be using the default FOSSASIA logo.

### PR DESCRIPTION
**Pull request by the-dagger**
Fixes #619 
Fixes #585 
Fixes #643
@mananwason I am still not able to copy the json files to assets directory.
Could you please have a look at it?
[https://github.com/the-dagger/open-event-android/blob/aa42d7cf1bde91e37bf880846254ef31cf13174d/apk-generator/scripts/appgenserver.py#L148](https://github.com/the-dagger/open-event-android/blob/aa42d7cf1bde91e37bf880846254ef31cf13174d/apk-generator/scripts/appgenserver.py#L148)
The image is getting copied into mipmap directory properly.

### CODE REVIEW

**Comment by mananwason** [comment]
Sure @the-dagger Will take a look asap

**Comment by the-dagger** [comment]
Added commit to fix #585

**Comment by the-dagger** [comment]
@mananwason please check and merge this

**Comment by the-dagger** [comment]
@mananwason the latest commit fixes #643

**Comment by mananwason** [comment]
@the-dagger I'm reviewing this currently

**Comment by mananwason** [comment]
LGTM

**Pull request merged**
