### PR TITLE
fix: Show only upcoming or ongoing events

### LINKED ISSUE #1748: Show only upcoming or ongoing events
**Describe the feature you'd like**
Currently all events are showing according to search location.

**Would you like to work on the issue?**

Working on it.

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #1748

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Apply server-side filter for this

**Comment by liveHarshit** [comment]
> Apply server-side filter for this
How filter is being used in the server. It is showing a blank box in the example. Please help.
image

**Comment by nikit19** [comment]
@liveHarshit https://flask-restless.readthedocs.io/en/latest/filtering.html

**Comment by liveHarshit** [comment]
It should like that `{"name":"ends-at","op":">","val":"%${System.currentTimeMillis()}%"}`, Here `ends-at` need to convert in mili seconds. But before query cannot retrieve the event. Please help!

**Comment by iamareebjamal** [comment]
See date range queries on the frontend.

**Comment by uds5501** [comment]
@liveHarshit This filter is the one used in Upcoming events in frontend, let me know if you require any assistance


https://github.com/fossasia/open-event-frontend/blob/125f26b44bd8f9a98710959ddae70c76068284f4/app/routes/index.js#L13-L123

**Comment by liveHarshit** [comment]
Updated

**Pull request merged**
