### PR TITLE
chore: Release v0.4.0

### PR DESCRIPTION
**Pull request by liveHarshit**
Ready to merge after PR #1894 got merged and Issue #1895 solved

### CODE REVIEW

**Comment by liveHarshit** [comment]
Ready to merge.

**Comment by liveHarshit** [comment]
Not ready to merge. The app is freezing in API 28. Testing.

**Comment by liveHarshit** [comment]
Ready to merge after PR #1922 and #1924 IMO. 
@anhanh11001 Please test if you find any major bug?

**Comment by anhanh11001** [comment]
@liveHarshit for now, not really major bugs that I could find

**Pull request merged**
