### PR TITLE
fix: Improve UI in fragment_favorite

### LINKED ISSUE #1122: Improve UI in fragment_favorite
**Describe the chore**
The current textsize is too small.
UI can be improved.

**Would you like to work on the issue?**

- [x] Yes

### PR DESCRIPTION
**Pull request by somenath1435**
Fixes #1122 

Changes: Initially the textsize was too small.
The textsize has been incresed.
Overall UI is improved.

Screenshots for the change:

Before:-
whatsapp image 2019-02-19 at 2 51 47 am

After:-
whatsapp image 2019-02-19 at 2 51 47 am 1

### CODE REVIEW

**Comment by somenath1435** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
I believe it was fine as it was

**Comment by somenath1435** [comment]
@iamareebjamal I believe the initial textsize is too small.

**Comment by somenath1435** [comment]
@iamareebjamal please give your opinion

**Pull request closed without merging**
