### PR TITLE
fix: Use thumbnail attribute for Speaker API

### LINKED ISSUE #1264: Size of Speaker Images to very large.
**Actual Behaviour**
Just installed the app on my device and after 10mins of use the app has used 300MB of mobile data. 
The size of speaker images is the major reason behind this.
Size of some images is as high as 6.2MB. (`Speaker` - Blair Layton, `Image` - https://storage.googleapis.com/eventyay.com/events/6/speakers/2312/photo/TXZMK1JFUm/f3069efd-8cdf-4786-9e59-046f95f41440.png)

**Expected Behaviour**
The images must be compressed using `tinypng` or `pngcrusher`. I guess the same has been done in the project `2017.fossasia.org`. We can also reduce size of Sponsor images.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #1264

Use `thumbnail` attribute from Speaker API to show thumbnails instead of photo

Using `photo` attribute for displaying images in SpeakerListFragment or Event Detail Activity
consumes large amount of data as full size images need to be downloaded. Using server side
resized images by using `thumbnail` or `icon` attribute saves from downscaling these photos
by a 3rd party application.

Screenshots: 
device-2017-04-10-225531
device-2017-04-10-230031
device-2017-04-10-230051
device-2017-04-10-230141

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This also saves up from using 3rd party applications as proposed in #1343

**Comment by iamareebjamal** [comment]
Please review @the-dagger @mariobehling

**Comment by iamareebjamal** [comment]
@the-dagger Please take a look

**Comment by the-dagger** [comment]
Yeah, this makes sense.
Are the images pixelated or not?

Can you add a screenshot for changes?

**Comment by iamareebjamal** [comment]
@the-dagger Since we only use thumbnail attribute for small images, they look fine. Still loading the full image for detail view

**Comment by the-dagger** [comment]
Ok, looks good now :+1:

**Pull request merged**
