### PR TITLE
Fix issue #831

### PR DESCRIPTION
**Pull request by vishwesh3**
Issue #831 
Now on  scroll progress bar comes at top and fixed at top.
videotogif_2016 12 19_14 13 00

### CODE REVIEW

**Comment by mananwason** [comment]
@vishwesh3 This doesn't look that good. You have changed the length of the toolbar by adding the progressbar to the appbarlayout. Please rectify this and squash changes here. Thanks

**Comment by vishwesh3** [comment]
@mananwason please have a look.

videotogif_2016 12 20_13 17 57

**Comment by mananwason** [comment]
@vishwesh3 Looks better but I believe the gap between toolbar and progress bar should be fixed as well. Please work on that.

**Comment by vishwesh3** [comment]
@mananwason I tried 
`android:layout_marginBottom="-8dp"
android:layout_marginTop="-4dp"`

But i am not able to achieve that. Can you please help me out?

**Comment by mananwason** [comment]
@vishwesh3 Away from my laptop for a few days. Will check and get back to you.

**Comment by niranjan94** [comment]
@vishwesh3 the base branch has been updated. Please make a fresh PR with your changes. Sorry for the inconvenience :sweat_smile:

**Pull request closed without merging**
