### PR TITLE
feat: Event can be stored directly in Calendar

### LINKED ISSUE #81: feat : Open Calendar when Date is clicked
The app should open an explicit Intent of Calendar when the date present in event details is clicked. This will directly help the user to mark the event
*Will be working on it after #76

### PR DESCRIPTION
**Pull request by dreadpool2**
Fixes #81 
videotogif_2018 06 06_21 08 40

### CODE REVIEW

**Comment by iamareebjamal** [comment]
It's not clear how to do this

**Comment by dreadpool2** [comment]
Actually in the eventbrite app it occurs like this, clicking on the date

**Comment by dreadpool2** [comment]
Should I make a calendar icon in the toolbar and make it clickable then ?

**Comment by iamareebjamal** [comment]
Yup

**Comment by dreadpool2** [comment]
videotogif_2018 06 07_18 54 08

**Comment by iamareebjamal** [comment]
Add it as an icon

**Comment by dreadpool2** [comment]
Actually in the meeting @mariobehling wanted the UI similar to EventBrite

**Comment by iamareebjamal** [comment]
@dreadpool2 Resolve conflicts

**Pull request merged**
