### PR TITLE
Better Map Activity #365

### PR DESCRIPTION
**Pull request by rohanagarwal94**
screenshot_2016-08-29-23-19-44_org fossasia openevent

@the-dagger @mananwason The above screenshot is what I have implemented in this PR . I have implemented the markers as per the Google i/o app markers. Regarding the overlay, I am quite not able to get the desired result since indoor map is not submitted to Google of this location. Below is the attached screenshot of the most apt overlay according to me. Also some the markers in the samples microlocation are incorrectly placed . Please review and suggest changes.

screenshot_2016-08-29-22-55-44_org fossasia openevent

### CODE REVIEW

**Comment by the-dagger** [comment]
@rohanagarwal94 Looks good to me but lets wait for @mananwason to review this.
Also this PR has conflicts, could you have a look at that?

**Comment by the-dagger** [comment]
@rohanagarwal94 Are you working on this?

**Comment by rohanagarwal94** [comment]
@the-dagger Manan did not get back to me regarding the pr. So don't know further changes/enhancements. Suggestions from u???
Though will contribute again in a week's tym due to exams.

**Comment by the-dagger** [comment]
@mananwason Could you take a look?
Also @rohanagarwal94 The PR has merge conflicts so I would suggest you to resolve them too while manan responds.
Cheers.

**Comment by mariobehling** [comment]
@rohanagarwal94 Sorry for taking a long time for the PR. Please resolve conflicts, so we can proceed. Thank you.

**Comment by rohanagarwal94** [comment]
@mariobehling I have removed the conflicts, please suggest further changes.

**Comment by mariobehling** [comment]
@rohanagarwal94 Sorry about that, but there was another PR that had conflicts. Kindly help to resolve it, please.

**Comment by mariobehling** [comment]
I am closing this PR due to inactivity. If relevant commit again, please. Thank you.

**Pull request closed without merging**
