### PR TITLE
fixes issue #1019

### PR DESCRIPTION
**Pull request by arp95**
Fixes issue #1019 

Changes: [Add here what changes were made in this issue and if possible provide links.]

made changes to the schedule activity which has a bookmark status along with it as in other activities displaying the tracks.

Also made changes to the day fragment where adapter code was shifted to onResume() for better updation in the bookmark status.

Screenshots for the change: 

16121978_10210242083923001_736853542_o 1

### CODE REVIEW

**Comment by arp95** [comment]
@the-dagger @mananwason please have a look and take the appropriate action.

**Comment by arp95** [comment]
@mananwason please have a look at the pr.

**Comment by Abhi2424shek** [comment]
@arp95 can you fix the issues highlighted by the codeacy-bot

**Comment by arp95** [comment]
@Abhi2424shek 
actually its asking me to make a member of bindview private but doing that passed the codacy bot issue but failed the travis build saying the members of bindview cannot be private.
Just have a look and please tell where im going wrong.

**Comment by Abhi2424shek** [comment]
Huh then leave it, encapsulation!!

**Comment by arp95** [comment]
@mananwason have resolved issues. now you can have a look and take action.

**Comment by saketkumar95** [comment]
@arp95 Resolve the codacy issue and squash your commits. :)

**Comment by arp95** [comment]
@saketkumar95 all the checks have passed. Dont know which issue you are talking about.

**Comment by saketkumar95** [comment]
yeah i just saw the comments, missed it. Squash the commits then. :)

**Comment by arp95** [comment]
Closing this pr due to inactivity.

**Pull request closed without merging**
