### PR TITLE
fix: Improvement in Welcome Screen

### LINKED ISSUE #1113: Improvement in Welcome Screen
**Describe the chore**
The image size and text size is increased

**Would you like to work on the issue?**
- [x] Yes

### PR DESCRIPTION
**Pull request by somenath1435**
Fixes #1113 

Changes: Changes in UI of Splash Screen(Image size and Text size increased)

Screenshots for the change:

Before:-
whatsapp image 2019-02-16 at 7 28 16 pm

After:
whatsapp image 2019-02-16 at 6 33 49 am

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This is not splash screen. Please post before image as well

**Comment by somenath1435** [comment]
@iamareebjamal 
I've only increased the size of image view , and the textview "we'll show you what's good near you"

**Comment by somenath1435** [comment]
@iamareebjamal 
Also I changed the name of issue and PR

**Comment by iamareebjamal** [comment]
Yes still post before image

**Comment by somenath1435** [comment]
@iamareebjamal I've added before and after screenshots

**Pull request merged**
