### PR TITLE
refactor: Break MainActivity methods into maintainable blocks (#1370)

### PR DESCRIPTION
**Pull request by iamareebjamal**
Follow up from #1370 

Breaks the monolithic and large methods into maintainable functions
Changes:
- Break the monolithic and large methods into maintainable functions
- Remove repetitive operations by encapsulating in methods
- Remove warnings over redundant declarations

### CODE REVIEW

**Comment by the-dagger** [comment]
Did you make changes to the fdroid variant?
That was the file causing issues iirc.

**Comment by iamareebjamal** [comment]
No I didn't change any FDroid version. But I'll take a look

**Comment by the-dagger** [comment]
Just run the commands which travis runs while compiling the app and see if there are any errors.

**Comment by iamareebjamal** [comment]
Ok. Travis build was passing though. I'll try again

**Comment by iamareebjamal** [comment]
@the-dagger Both locally and online, all checks and build are passing. Could you take a look?

**Comment by harshitagupta30** [comment]
@the-dagger may I know the reason for closing this? Just wanted to know as Mario has asked me to review it. :) :+1:

**Pull request closed without merging**
