### PR TITLE
feat: Add log out dialog in settings fragment.

### LINKED ISSUE #1579: Add logout dialog in settings
**Describe the feature you'd like**

Show logout dialog when account preference in clicked in settings fragment as in Eventbrite.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by angmas1**
Fixes #1579 

Changes: Added logout dialog when account is clicked in settings fragment.

Screenshots for the change:
ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by angmas1** [comment]
@liveHarshit @nikit19 please review

**Comment by angmas1** [comment]
I tried using anko alert dialog, but it didn't look good. It is using incorrect theme. I searched and found that to correct it, I will have make custom layout. So, I think this is better.

**Comment by aggarwalpulkit596** [comment]
Make a custom layout 
and reuse this customdialog ui everywhere  https://link.medium.com/dVP9qvPgNV

**Comment by iamareebjamal** [comment]
Why should we make a custom layout when we can do without it. I agree, let's remove it and use only if we realize that it makes our code much better than it currently is. Right now, it doesn't

**Comment by angmas1** [comment]
@iamareebjamal please review

**Comment by angmas1** [comment]
Please review before PR becomes stale

**Comment by angmas1** [comment]
Resolved conflicts

**Pull request merged**
