### PR TITLE
Closing keyboard on search click

### PR DESCRIPTION
**Pull request by heysadboy**
@mananwason Sorry for last time. Here is the pull request to solve the issue
https://github.com/fossasia/open-event-android/issues/886

### CODE REVIEW

**Comment by the-dagger** [comment]
Hey @heysadboy this was done in #1018 for all of the activities in the app, so closing this for now.
Thanks for the PR.

**Comment by heysadboy** [comment]
@the-dagger I understand. Thanks for looking up.

**Comment by free4murad** [comment]
@the-dagger 
I have solved issue #966 for all activities but SpeakerListFragment.
while working on the issue I saw that @heysadboy is working on issue #886 .
So I didn't change this.
Please reopen this and review.

**Comment by the-dagger** [comment]
Thanks for the heads up @free4murad.

**Comment by heysadboy** [comment]
@free4murad @the-dagger Thanks I didn't know that.

**Pull request merged**
