### PR TITLE
[*]  updated android codebase with

### PR DESCRIPTION
**Pull request by nisrulz**
- support for api 24
- updated dependencies
- updated android tools plugin
- gradle wrapper to v2.13

### CODE REVIEW

**Comment by mananwason** [comment]
Hey @nisrulz. You need to change the version numbers in the travis yaml files as well, otherwise the build will keep failing.

**Comment by the-dagger** [comment]
Also @nisrulz, you'll need to squash the commits before we can merge it. 
Cheers.

**Comment by nisrulz** [comment]
You get to squash and merge in Github now. Hopefully that shouldn't be a problem when merging. 

Your android app also uses a deprecated api for map functionality 
```
> Building 55% > :app:compileGoogleplayDebugJavaWithJavacMap = getMap();
               ^
  symbol:   method getMap()
  location: class MapsFragment
Note: Some input files use or override a deprecated API.
```

which is why the build is failing now, provided I have already update the travis.yml and build.gradle files.

**Comment by the-dagger** [comment]
Ok, I'll check the app.
I did notice this in the Travis logs. 
Thanks. :+1:

**Comment by the-dagger** [comment]
Looks good, merging.

**Pull request merged**
