### PR TITLE
Fixing Issue #804

### PR DESCRIPTION
**Pull request by rhemon**
Since we are using scrollable TabLayout, according material design it should have a marginStart of 72p.

### CODE REVIEW

**Comment by the-dagger** [comment]
There are commits from your earlier PR as well.
Ideally you should update your fork and then send a pull request,

**Comment by rhemon** [comment]
Oops sorry, should I try rebasing?

**Comment by the-dagger** [comment]
Yep

**Comment by rhemon** [comment]
I don't know why but I seem to have some unknown comits that I am not well aware of, so gonna get rid of do a new pull request, sorry.

**Pull request closed without merging**
