### PR TITLE
fix: Order eventId null bug

### LINKED ISSUE #299: add sparse fields for order
working on it 👍

### PR DESCRIPTION
**Pull request by simarsingh24**
fixes #299

### CODE REVIEW

**Comment by simarsingh24** [comment]
@iamareebjamal earlier eventId and attendees were null which was causing error while inserting order in db, now fields are fetched but i am getting foreign key constraint failed error

**Comment by simarsingh24** [comment]
@iamareebjamal but we are calling create order after attendee is created and inside attendeeService, it inserts attendee into the database 
```
 fun postAttendee(attendee: Attendee): Single<Attendee> {
        return attendeeApi.postAttendee(attendee)
                .map {
                    attendeeDao.insertAttendee(it)
                    it
                }
    }

```

**Comment by iamareebjamal** [comment]
But you are getting all the orders of the event, not necessary that the attendee associated with that order exists in DB

**Comment by simarsingh24** [comment]
@iamareebjamal What should be done then? Should we just change 
```
 fun placeOrder(order: Order): Single<Order> {
        return orderApi.placeOrder(order)
                .map {
                    orderDao.insertOrder(it)
                    it
                }
    }
```
to a completable and dont store it in DB anyways we will be making request to the API for getting orders

**Comment by simarsingh24** [comment]
@iamareebjamal should I proceed with this?

**Comment by iamareebjamal** [comment]
- Either don't store the orders for which we don't have attendees
- Or fetch attendees with orders

**Comment by simarsingh24** [comment]
@iamareebjamal Updated

**Comment by simarsingh24** [comment]
@dreadpool2 please review and merge this

**Pull request merged**
