### PR TITLE
feat: Added Hindi Translations

### LINKED ISSUE #1275: Add Hindi Translation
**Describe the feature you'd like**
MultiLanguage Support: Add Hindi Translations

**Would you like to work on the issue?**

- [x] Yes

### PR DESCRIPTION
**Pull request by somenath1435**
Fixes #1275 

Changes: Added Hindi Translations to the app.

### CODE REVIEW

**Comment by somenath1435** [comment]
@iamareebjamal @nikit19 please review

**Comment by somenath1435** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
Many translations are wrong. It'll be worse for a person who is using hindi as a language option than seeing the strings in English. I think the same thing is true for other language translations. But I could verify only this because I understand Hindi. Internationalization is not our priority right now

**Comment by somenath1435** [comment]
@iamareebjamal I'm not proficient in hindi, you can suggest changes

**Comment by iamareebjamal** [comment]
That's the point. Why add changes which are not required and wrong. Obviously I'm going to spend time reviewing and suggesting on other PRs solving actual issues

**Comment by aman210697** [comment]
Well, there is a cool hack to translate the strings using google sheets.

**Pull request merged**
