### PR TITLE
fixes issue #843

### PR DESCRIPTION
**Pull request by arp95**
improvement in the ui as shown below:
15536743_10209924523784196_1585883232_o
15502660_10209924526424262_2089863697_o

### CODE REVIEW

**Comment by the-dagger** [comment]
This doesn't looks like an improvement to me.
I'd suggest you to leave the tracks as they are and remove the cards from the location Activity and use a list in its place if you are going for a UI enhancement.

**Comment by arp95** [comment]
@the-dagger the overall purpose of card view is to make ui better. or am i overdoing ui stuff over here?

**Comment by the-dagger** [comment]
According to material design guidelines, cards should not be used in lists containing less than 3 lines of content, as it decreases the readability of content.
[https://material.google.com/components/cards.html#cards-usage](https://material.google.com/components/cards.html#cards-usage)

**Comment by arp95** [comment]
Thanks for the info. Will keep that in mind.

**Comment by the-dagger** [comment]
The issue is still open.
You can send a pull request implementing my suggestions if you'd like to.

**Comment by arp95** [comment]
Yeah sure. Doing that.

**Pull request closed without merging**
