### PR TITLE
Fixed Keyboard hiding bug on Navigation Drawer Opening.

### PR DESCRIPTION
**Pull request by GauravChaddha1996**
Soft Input keyboard now gets hidden if it was open whenever the navigation drawer is opened.

### CODE REVIEW

**Comment by GauravChaddha1996** [comment]
Can anybody tell me what went wrong in the travis CI build

**Comment by championswimmer** [comment]
@GauravChaddha1996 I'll fix the travis issue. The QA tests are failing.

**Comment by GauravChaddha1996** [comment]
Thank you.

**Comment by GauravChaddha1996** [comment]
@championswimmer is the QA tests fixed?

**Comment by GauravChaddha1996** [comment]
@championswimmer No worries i cloned the codebase again and made the same changes and this time travis CI build went through.Please consider the pull request.

**Pull request closed without merging**
