### PR TITLE
Add gradle command that auto detects user's OS and builds the project accordingly

### PR DESCRIPTION
**Pull request by the-dagger**
@championswimmer 
This will fix the
 "Error: CreateProcess error=2, The system cannot find the file specified" that happens with Windows users while building the project.
Built it on both Windows and Linux and the project builds perfectly fine.

### CODE REVIEW

**Comment by the-dagger** [comment]
@mananwason Could you have a look here?
I have discussed this issue with Arnav and he acknowledged the issue while building the project on Windows.
This script will auto detect user's OS and build accordingly. 
Cheers.

**Comment by mananwason** [comment]
@the-dagger Again this issue is not with the project. If you have git in your environment path variable, this will build fine.

**Comment by the-dagger** [comment]
Ok, I'll recheck this and will let you know.

**Comment by mananwason** [comment]
:+1: Closing this for now then.

**Comment by the-dagger** [comment]
@mananwason @championswimmer I have added git to the environment path variable and the problem persists.
I have even checked if I did it properly by running `git --version` in CMD and it returns `git version 2.6.4.windows.1`
Which means I do have git in my path.
The error that i get on gradle sync is 
`Error:(4, 0) CreateProcess error=2, The system cannot find the file specified`

**Comment by championswimmer** [comment]
@mananwason, a slight Change in the command is needed for Windows, even if
git is in path. @the-dagger is right on that

**Comment by the-dagger** [comment]
@championswimmer this PR looks good or are there some changes to be made?

**Comment by opticod** [comment]
I tried building the project in windows but I didn't get any errors and the build was successful. Are your SDKs are updated one?

**Comment by the-dagger** [comment]
@opticod Yep they are.

**Comment by mananwason** [comment]
@championswimmer @the-dagger @opticod I also tried building on 2 windows machines and I didn't face any errors :confused:

**Comment by the-dagger** [comment]
@mananwason Reverted back to the stable build of windows 10 and it builds correctly.
Installed the beta build again and the build fails.
Maybe its because of that.
Cheers.

**Comment by mananwason** [comment]
Cool :+1

**Pull request closed without merging**
