### PR TITLE
fix: upgrade app database to version 2

### LINKED ISSUE #1538: Search not working in production app
Nothing gets searched. Throws error fetching event 

Diagnose what's happening

### PR DESCRIPTION
**Pull request by anhanh11001**
Fixes #1538 

The database is upgraded into version 2. I tested by checking out to old commits, build that APK and then check out to the latest APK to update. Everything seems to work fine now.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@anhanh11001 Please create branch from master

**Comment by anhanh11001** [comment]
oh right, sorry I didn't notice that

**Comment by iamareebjamal** [comment]
It is still created from development

Run these commands:

```
git reset HEAD^
git stash
git reset --hard master
git stash pop
git push origin 1538_upgrade_database_version -f
```

**Comment by anhanh11001** [comment]
When I run git reset HEAD^, it gives the line
`More?`
What command should I run?

**Comment by iamareebjamal** [comment]
I have updated the commands

It should show you something like this

```
Unstaged changes after reset:
...
```

**Comment by anhanh11001** [comment]
I have followed those command. Please let me know if it is still not correct?

**Comment by iamareebjamal** [comment]
It's correct :+1:

**Pull request merged**
