### PR TITLE
feat: improve UI of events and event details

### LINKED ISSUE #91: Make events UI look standard
no use of pink colour in share items
Working on it

### PR DESCRIPTION
**Pull request by nikit19**
fixes #91 
UI changes.
add location name instead of description in card.
Shift share event from fab to menu
Remove start year.
Change colors.
Changed text styles
Add margin to horizontal divider.
Reduce Details imageview size.
screenshot_20180609-160055
screenshot_20180609-160137

### CODE REVIEW

**Comment by dreadpool2** [comment]
@nikit19 Woah looks great !

**Comment by iamareebjamal** [comment]
The card should encapsulate the entire event and not just the pic

**Comment by nikit19** [comment]
@iamareebjamal How do you suggest making the corners of the imageView round? This seemed to me the simplest way as only XML changes were required

**Comment by iamareebjamal** [comment]
No need of making image round

**Comment by nikit19** [comment]
PR updated. Please review
screenshot_20180609-171313

**Comment by iamareebjamal** [comment]
There's no rounded corner and elevation on the card

**Comment by nikit19** [comment]
Yes I removed that on purpose to make the UI look more like Eventbrite
screenshot_20180609-172948

**Comment by iamareebjamal** [comment]
Eventbrite has a well-designed UI which is following their guidelines. We don't have a design prototype so we must follow material design guidelines to at least look professional

**Comment by iamareebjamal** [comment]
Remove padding from imageview

**Comment by nikit19** [comment]
Removed padding from imageview
screenshot_20180609-192644

**Pull request merged**
