### PR TITLE
add todofy badge - shows remaining todos

### PR DESCRIPTION
**Pull request by championswimmer**
Signed-off-by: Arnav Gupta <championswimmer@gmail.com>

### CODE REVIEW

**Comment by creativepsyco** [comment]
I don't know how this helps, apart from sending us bulk emails?

**Comment by championswimmer** [comment]
Lists all TODOs in code by parsing //TODO comments.

There are often todos in code (like the two there are) without
corresponding issues on github

**Comment by creativepsyco** [comment]
:+1:

**Comment by championswimmer** [comment]
TODOs and their status can be checked here
https://todofy.org/r/fossasia/open-event-android

**Pull request merged**
