### PR TITLE
feat: Add submit feedbacks

### LINKED ISSUE #1633: Submit Feedbacks for events
**Describe the feature you'd like**
Currently, there is no option to provide feedback for an event.
There should be an option to provide feedback for events for logged in users

**Would you like to work on the issue?**
- [x] Yes

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Fixes #1633 

Changes: Added option to submit feedback

Screenshots for the change:
screenshot-1555731668958
screenshot-1555733486736

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@nikit19  @iamareebjamal is the layout okay or I need to improvise it?

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
PRF

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal why closed ?

**Comment by iamareebjamal** [comment]
By mistake

**Comment by iamareebjamal** [comment]
Can't reopen it. It is saying the submitFeedback branch was force-pushed or recreated

**Comment by aggarwalpulkit596** [comment]
i'll make a new pr

**Pull request closed without merging**
