### PR TITLE
fix: Lenient parsing and error handling throughout the app

### LINKED ISSUE #1662: Add more lenient parsing when inserting into database
**Actual Behaviour**

Currently, parser and processor assumes that there is no null field present in the JSON response, saving null objects in the process. 

**Expected Behaviour**

There should be checks and more verbose messages indicating there is error in parsing the said JSON

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #1662 

Changes:
- Create abstract ResponseProcessor to do common tasks which supports lenient parsing and verbose logging
- Add null checks wherever possible
- Reduce HTML loading code complexity by creating a utility method
- Change RealmRepository to adopt to partial or null updates
- Add option to delete version if error while parsing so that full download happens next time

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@mahikaw @arp95 You can pull these changes, set the API link in `config.json` and test the app, you may also use stetho to see if data is being parsed correctly

It won't crash anymore, event with null tracks, etc

**Comment by arp95** [comment]
@iamareebjamal it was a pain right now. dont know it was becasue of realm or something else but before it used to work fine.
thanks for this. having a look.

**Comment by iamareebjamal** [comment]
@arp95 Before realm, data was stored relationally, no no concept of getting sessions from tracks and vice versa, so we just got empty lists instead of nulls

**Comment by shreyasnbhat** [comment]
@iamareebjamal Does this fix #1641 too?

**Comment by iamareebjamal** [comment]
Doubt it. That's a date related issue. It definitely fixes the second bug you posted

**Comment by shreyasnbhat** [comment]
@iamareebjamal  I just tested out the app. It didn't happen now. I guess there exits a possibility where that issue might crop up again? What do you suggest I should do? Add null checks inside the date class?

**Comment by iamareebjamal** [comment]
@shreyasnbhat Yes, please do wherever possible

**Comment by iamareebjamal** [comment]
@arp95 @mahikaw @shreyasnbhat @Shailesh351 Please review the PR

This is quite high priority

**Comment by iamareebjamal** [comment]
@niranjan94 Please merge

**Comment by shreyasnbhat** [comment]
#1641 Needs to be solved before merge

**Comment by arp95** [comment]
@iamareebjamal sent the pr to your branch. rest seems fine.

**Comment by iamareebjamal** [comment]
@arp95 You removed a null check in your PR. The app will crash if the track name is empty

**Comment by arp95** [comment]
@iamareebjamal should i send the pr if i removed it?

**Comment by iamareebjamal** [comment]
I have not added that PR into the commits. Please take a look if there is any discrepancy, or else, we'll merge this PR

**Comment by arp95** [comment]
@iamareebjamal yeah thats fine. just one final thought, in some places we are checking the string using TextUtils.isEmpty() while in some places we are keeping the values null. just see whether its fine or not.
else its fine to merge as all the variables were covered with null checks.

**Comment by iamareebjamal** [comment]
We should use isEmpty everywhere, some places I am fixing. If you could please list all places where you saw null check, it'd really help me out

**Comment by arp95** [comment]
sure. having a look

**Comment by arp95** [comment]
have sent you the pr. have a look.

**Comment by Shailesh351** [comment]
@iamareebjamal sponsor list adapter also needs null check for url.
Please add.

**Comment by iamareebjamal** [comment]
@arp95 has sent a PR addressing the issue. It needs some changes, then it will be ready

**Comment by arp95** [comment]
sorry for delay.
having a look.

**Comment by arp95** [comment]
@iamareebjamal 
sent the pr at your branch. please have a look.

**Comment by iamareebjamal** [comment]
@Shailesh351 @shreyasnbhat @mahikaw Please review

**Comment by Shailesh351** [comment]
@arp95 @iamareebjamal please add ckeck for sponsor url. because If url for sponsor is null then it will crash app on clicking it.

https://github.com/iamareebjamal/open-event-android/blob/b781339bac292b594eeedcc4bebe6db5793d46d7/android/app/src/main/java/org/fossasia/openevent/adapters/SponsorsListAdapter.java#L115

**Comment by iamareebjamal** [comment]
@Shailesh351 Fixed. Please review now

**Comment by Shailesh351** [comment]
@iamareebjamal App crashing after download done because of date being null in saveEventDatesInRealm(start, end)

Here's logcat

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
                                                                            at java.util.Calendar.setTime(Calendar.java:1089)
                                                                            at org.fossasia.openevent.dbutils.RealmDataRepository.saveEventDatesInRealm(RealmDataRepository.java:485)
                                                                            at org.fossasia.openevent.dbutils.RealmDataRepository.lambda$saveEventDates$13(RealmDataRepository.java:500)
                                                                            at org.fossasia.openevent.dbutils.RealmDataRepository$$Lambda$15.run(Unknown Source)
                                                                            at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
                                                                            at io.reactivex.Completable.subscribe(Completable.java:1634) 
                                                                            at io.reactivex.Completable.subscribe(Completable.java:1622) 
                                                                            at org.fossasia.openevent.activities.MainActivity.syncComplete(MainActivity.java:379) 
                                                                            at org.fossasia.openevent.activities.MainActivity.access$lambda$0(MainActivity.java) 
                                                                            at org.fossasia.openevent.activities.MainActivity$$Lambda$4.run(Unknown Source) 
                                                                            at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:52) 
                                                                            at io.reactivex.subjects.CompletableSubject.onComplete(CompletableSubject.java:86) 
                                                                            at org.fossasia.openevent.utils.DownloadCompleteHandler.notifyComplete(DownloadCompleteHandler.java:77) 
                                                                            at org.fossasia.openevent.utils.DownloadCompleteHandler.onDownloadDone(DownloadCompleteHandler.java:146) 
                                                                            at org.fossasia.openevent.utils.DownloadCompleteHandler.access$300(DownloadCompleteHandler.java:23) 
                                                                            at org.fossasia.openevent.utils.DownloadCompleteHandler$EventHandler.onSponsorsDownloadDone(DownloadCompleteHandler.java:184)`

**Comment by iamareebjamal** [comment]
Which sample were you testing on?

**Comment by Shailesh351** [comment]
Default FOSSASIA https://eventyay.com/api/v1/events/6/ 
which is in config.json

**Comment by iamareebjamal** [comment]
Strange. Let me see

**Comment by iamareebjamal** [comment]
@Shailesh351 Well, the whole event is null :laughing:

**Comment by Shailesh351** [comment]
@iamareebjamal it is only api url. For event : https://eventyay.com/api/v1/events/6/event :sweat_smile: 

And all the time and date strings in TracksessionsActivity and Session details activity is displaying null.

**Comment by iamareebjamal** [comment]
This is because the API response regarding time has changed. Please create a new issue addressing the changes required

**Comment by iamareebjamal** [comment]
@the-dagger Please review and merge

**Pull request merged**
