### PR TITLE
fix: App exit on back pressed

### LINKED ISSUE #626: You can't exit the app using the back button
**Describe the bug**
You can't exit the app using the back button
**To Reproduce**
Open the app and press the back button

**Would you like to work on the issue?**

- [ ] Yes
- [X] No
- Other:

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
fixes #626
### GIF for the change
ezgif com-video-to-gif

### CODE REVIEW

**Comment by GOVINDDIXIT** [comment]
@nikit19  pls review

**Comment by GOVINDDIXIT** [comment]
Updated pls review

**Comment by GOVINDDIXIT** [comment]
@iamareebjamal 
As the Fragment lifecycle do not have onBackPressed(). So According to me alternative method to override onBackPressed() in Android 3.0 fragments can be done by creating an interface class OnBackPressedListener and Create class which implements skills of OnBackPressedListener and creating a listener and a method to set listener. But the current changes are also preforming same job. So I goes with it.

**Comment by iamareebjamal** [comment]
Fragments don't have onBackPressed, their container activity does. Find why it is not working

**Comment by GOVINDDIXIT** [comment]
@nikit19 pls review

**Comment by GOVINDDIXIT** [comment]
@iamareebjamal  The problem is with the stack generated. Currently the onBackPressed method is loading the event fragment  two times one with loadfragment and then with checkandLoad method. So I had cleared the stack generated everytime the user press the back button and located the user to Event Fragment which is required . Now the user can easily exit the as there is only 1 fragment in the stack.

**Comment by GOVINDDIXIT** [comment]
@iamareebjamal  I think the issue is solved pls review

**Comment by iamareebjamal** [comment]
This is still a workaround. I will see what can be done

**Comment by iamareebjamal** [comment]
Old and conflicting with the current logic

**Pull request closed without merging**
