### PR TITLE
Update location activity map activity

### LINKED ISSUE #1636: Map appears in background
**Actual Behaviour**

I think the visibility of cards should be changed when we click the map activity from Locations -> Any Session.

**Expected Behaviour**

Only map should be there.

**Steps to reproduce it**

Change visibility of components.

**Screenshots of the issue**

<table>
<td>

</td>
<td>

</td>
</table>

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Milestone 4.

### PR DESCRIPTION
**Pull request by mahikaw**
Fixes  #1636 and #1551 

Changes: 

- [X] Map doesn't appear in background now.

- [x] Map and calendar buttons don't disappear on pressing backbutton and then re-opening map activity.

### CODE REVIEW

**Comment by arp95** [comment]
@mahikaw as the change you did wasnt a large one, its good to submit the pr when you complete the entire work. doing in smaller part is when the work done is large.

**Comment by mahikaw** [comment]
@arp95 this was solely so as to solve #1636 . :)

**Comment by iamareebjamal** [comment]
@rohanagarwal94 The PR is work in progress :smiley:

**Comment by rohanagarwal94** [comment]
@iamareebjamal I thought it was only solving the map underlay problem. Didn't see the button problem in the issue mentioned. Apologies.

**Comment by iamareebjamal** [comment]
No, we shall ignore it :smile:

**Comment by mahikaw** [comment]
@iamareebjamal this is complete now. Please review.

**Comment by iamareebjamal** [comment]
@mahikaw As a general rule, please remove the WIP tag from issue description

**Pull request merged**
