### PR TITLE
Add progressbar on the app generator

### LINKED ISSUE #543: No progress info or bar on apk generator
After a user starts the generation process there is no progress in or bar showing up.

### PR DESCRIPTION
**Pull request by the-dagger**
Fixes #543 
@mariobehling @mananwason Please review and merge.
spectacle xmt308

### CODE REVIEW

**Comment by mariobehling** [comment]
I tested it and this implementation is buggy. Please implement as discussed here: https://github.com/fossasia/open-event-webapp/issues/595#issuecomment-240981096

**Comment by the-dagger** [comment]
@mariobehling This PR was not addressing #548 
This was meant for #543 which it fixes

**Comment by mariobehling** [comment]
@the-dagger Thanks for clarifying. It appeared at the same place like the progress bar in the web app and looked like implementing the same thing. Please re-add and fix both issues.

**Comment by the-dagger** [comment]
@mariobehling, ok I will send a Pull Request again.

**Pull request merged**
