### PR TITLE
Add share speaker info functionality

### PR DESCRIPTION
**Pull request by leeweijie**

### CODE REVIEW

**Comment by creativepsyco** [comment]
Hi @leeweijie we have merged a version of the feature in PR #165 . Can you take a look at some of the issues and check if you can work on those?

**Comment by leeweijie** [comment]
Hi @creativepsyco may I know what are the issues? There doesn't seem to be any issues mentioned in the share speaker functionality push request.

**Comment by creativepsyco** [comment]
The one that I merged has a better implementation

**Comment by leeweijie** [comment]
@creativepsyco yes, I understand that. What i'm meant was what were the issues you wanted me to work on in your previous comment. I browsed pr #165 but didn't see any issues there that I can help with. Thanks

**Comment by creativepsyco** [comment]
Nope I mean check out https://github.com/fossasia/open-event-android/issues if you are looking for something to work on :)

**Comment by mananwason** [comment]
@leeweijie Closing this.

**Pull request closed without merging**
