### PR TITLE
[DO NOT MERGE] packaged json parsing done

### PR DESCRIPTION
**Pull request by mananwason**

### CODE REVIEW

**Comment by the-dagger** [comment]
@mananwason lets close this and send new PRs only when @championswimmer has changed the project structure and added codacy to the branches.

**Comment by mananwason** [comment]
@the-dagger This is on my fork, so I don't think there should be any issues. @championswimmer Can start adding codacy to the master branch

**Comment by the-dagger** [comment]
@mananwason The current master will be gone.
`stable` will be the new `development`
and `shipping` the new `master`
#460

**Comment by mananwason** [comment]
Yeah I know that. That is not a problem. If @championswimmer requires to close this, he can do so.

**Comment by the-dagger** [comment]
Oh, ok then. :+1:

**Comment by championswimmer** [comment]
This will become invalid after the renamings. Make PR to new development branch then ? Ok @mananwason ?

**Comment by mananwason** [comment]
Okay @championswimmer. Closing this then.

**Pull request closed without merging**
