### PR TITLE
made app re:Data compatible

### PR DESCRIPTION
**Pull request by mananwason**
@creativepsyco Should we merge this right now?

### CODE REVIEW

**Comment by creativepsyco** [comment]
yeah you can merge this anytime.

**Comment by mananwason** [comment]
@creativepsyco I am merging this.

**Comment by mariobehling** [comment]
ok, good. How about links of speakers and social media? What is the implementation here?

**Comment by mananwason** [comment]
@mariobehling if you click any speaker card, the speaker detail activity comes up. There you can find buttons with speaker links namely linkedin, twitter, Facebook, Github.

**Pull request merged**
