### PR TITLE
App crashing on clicking on any member  after 5th member on speaker's list #107 FIXED

### PR DESCRIPTION
**Pull request by vjs3**
On clicking on any member starting from member number 6 (i.e starting from guy named Tarek Ahmed) either app get crashed or lead us to the home screen. It is giving CursorIndexOutOfBoundsException.
I have resolved the issue and now it is working fine for all the rest members of the list as well.

### CODE REVIEW

**Comment by vjs3** [comment]
It is working fine in my local machine.Can please any one help me why this build gets failed?

**Comment by mananwason** [comment]
@vjs3 It is a travis issue. I have restarted the build. Can you please change the commit message to something more suitable.

**Comment by vjs3** [comment]
@mananwason I have changed it.

**Comment by mananwason** [comment]
@vjs3 you have changed the title of the PR. Please change the commit message.

**Comment by vjs3** [comment]
I will do that.Sorry for the inconvenience caused, I am new to open source and will try not to do such mistakes in future.

**Comment by vjs3** [comment]
@mananwason it is still failing?Does this have to something with my code or just a travis issue?

**Comment by mananwason** [comment]
@vjs3 It has passed now

**Comment by vjs3** [comment]
yes :smile: Thanks for all your help :)

**Comment by vjs3** [comment]
@mananwason is there still any issue with code as Its not merged with the main codebase.Please let me know if there is any.

**Comment by vjs3** [comment]
@mananwason Hi someone told me on irc that because I might not make changes to commit message that's why my request is not merged.So do I need to make a new pull request with changed commit message?

**Comment by mananwason** [comment]
@vjs3 Looks good. I am merging this :smiley:

**Comment by vjs3** [comment]
Thankyou @mananwason and sorry for bothering you lot of times.

*Vishwajeet Srivastava*
B.Tech, Pre-Final (Computer Science and Engineering)
The LNM Institute of Information Technology
Mob:+91-9461787316

**Pull request merged**
