### PR TITLE
set statusbar and navbar color on Lollipop and above

### PR DESCRIPTION
**Pull request by koushikraj**
Signed-off-by: Arnav Gupta <championswimmer@gmail.com>

Fixes #[Add issue number here. Note: This will automatically close the issue. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@koushikraj Why such an old commit from @championswimmer through @opticod branch ? :confused:

**Comment by koushikraj** [comment]
oho sry by mistake

**Comment by iamareebjamal** [comment]
Shall I close this then @koushikraj

**Comment by koushikraj** [comment]
Ohk

**Pull request closed without merging**
