### PR TITLE
feat: Add sticky headers in the recyclerview(trackRecyclerView)

### LINKED ISSUE #1291: UI-Improvement : Update Recyclerview to sticky header recycler view
**Actual Behaviour**

-There is simple Recycler view in App
-item_schedule.xml which is used in ScheduleFragment is not more user friendly.

schedulefragment_with_sortorder_starttime_before

schedulefragment_with_sortorder_tracks_before

tracksfragment_before

**Expected Behaviour**

-Improve UI and UX.

-Update to Sticky Header Recycler view for grouping of Recyclerview items which starts with same Alphabet or time which will improve UI and UX.

-Update item_schedule.xml . 

schedulefragment_with_sortorder_starttime_after

schedulefragment_with_sortorder_tracks_after

tracksfragment_after

final_demo

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Shailesh351**
Fixes #1291 

Changes: 
modified files :
[TracksFragment.java](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java)
[TracksListAdapter.java](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/adapters/TracksListAdapter.java)

Screenshots for the change: 
videotogif_2017 03 13_16 12 32

### CODE REVIEW

**Comment by free4murad** [comment]
@Shailesh351
Before spending a PR (which adds new functionality or changes UI) you should ask the project maintainers if they are ok with what you are trying to do.

S

**Comment by harshitagupta30** [comment]
@Shailesh351 It's considered a good practice to take maintainer's approval before sending a PR. Thanks for your effort. Is it really required when tracks are already sorted in alphabetical order?

**Comment by the-dagger** [comment]
Please add screenshot for the change

**Comment by Shailesh351** [comment]
@harshitagupta30 Will keep in mind in future :smiley:

**Comment by Shailesh351** [comment]
@the-dagger Please review this PR

**Comment by mananwason** [comment]
I don't think this adds any valu.

**Pull request closed without merging**
