### PR TITLE
update project to use Retrofit2.

### PR DESCRIPTION
**Pull request by humazed**
update project to use Retrofit2.
	-update test classes as well.
	-added all reqered liberaries.

**there is some minor changes left in error handling will be finished soon but there is no bugs introduced.

### CODE REVIEW

**Comment by championswimmer** [comment]
I'd probably wait till it gets out of beta. (Both gson and retrofit)

**Comment by humazed** [comment]
why!!
the current version is very stable and I just have used the basic API of Retrofit which is highly unlikely to be changed when the final release comes out.

**Comment by championswimmer** [comment]
I presume it got out of Beta yesterday

**Comment by humazed** [comment]
so I think it's ready to be merged.

**Comment by mananwason** [comment]
@humazed This is not at all ready to be merged. There are lot of commits here which have been already merged into codebase, remove them.

**Comment by humazed** [comment]
I not sure about what should I do to make my Pull request accepted. 
should I delete this Pull request and create a new one.

**Pull request closed without merging**
