### PR TITLE
Solving Issue #604

### PR DESCRIPTION
**Pull request by chiragw15**
Now Speakers list looks like this.
screenshot_20160819-192927

### CODE REVIEW

**Comment by mananwason** [comment]
@chiragw15 I don't know. This doesn't look good. The UI is not so good. Could you come up with something else. Thanks!

**Comment by chiragw15** [comment]
No problem @mananwason . What about something like this: 
zqd8b

**Comment by mananwason** [comment]
@chiragw15 I am no UI expert but this doesn't look so good :/

**Comment by chiragw15** [comment]
Alright , I'll try something else :) @mananwason

**Comment by mariobehling** [comment]
@chiragw15 To make our workflow more transparent, we kindly ask contributors to file an issue first and outline ideas before implementation. An overhaul of colors and basic UI needs to be done at some point, but at the moment there are still basic functional issues that need to be solved. Please help us to solve existing issues first. And for anything else, please file an issue first as well and then align pull requests to issue (one issue = one pull request). I am closing this PR therefore. Thank you.

**Comment by chiragw15** [comment]
@mariobehling Sir, I did file an issue i.e issue #604 . But the mistake I made is that I didn't outline ideas before implementation. I'll be more careful next time. Sorry for trouble.

**Comment by mariobehling** [comment]
Ah, yes I see it now in the heading. Please add issues in the description in future, where we can easily click and check the discussion on them.

**Pull request closed without merging**
