### PR TITLE
chore: New screenshots added in readme

### LINKED ISSUE #940: Update the screenshots in the Readme.md file
**Describe the chore**
The screenshots in the readme are old and need to be updated.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by rob729**
Fixes #940

Changes: 
Added new screenshots in the readme file.

Screenshots for the change:
https://github.com/rob729/open-event-android/blob/development/README.md

### CODE REVIEW

**Comment by liveHarshit** [comment]
These screenshots are with empty events. I will share some screenshots with you. Update them.

**Comment by rob729** [comment]
@liveHarshit Ok

**Comment by rob729** [comment]
@liveHarshit I have done the suggested changes.

**Comment by liveHarshit** [comment]
> @liveHarshit I have done the suggested changes.

Good, please add two or three more screenshots from previous to make look even or IMO 3*3 is the best combination. And arrange them in order. Currently, ticket details are showing first and tickets section showing after that.

**Comment by liveHarshit** [comment]
Have a look at this arrangement - 
https://github.com/fossasia/susi_android/blob/development/README.md
https://raw.githubusercontent.com/fossasia/susi_android/development/README.md

**Comment by GOVINDDIXIT** [comment]
@liveharshit Are events back on the server now ? I tried creating them but getting only verified acount can create events. Which is again an issue with server.

**Comment by liveHarshit** [comment]
> @liveHarshit Are events back on the server now ? I tried creating them but getting only verified acount can create events. Which is again an issue with server. Earlier I was able to create events.

I have replaced debug server to release server in gradle file.

**Comment by liveHarshit** [comment]
> @liveHarshit Please review the changes.

It's same. Too much blank space at right. You can use following table - 
```
<table>
  <tr>
    <td><img src="image_url" height = "480" width="270"></td>
    <td><img src="image_url" height = "480" width="270"></td>
    <td><img src="image_url" height = "480" width="270"></td>
  </tr>
  <tr>
    <td><img src="image_url" height = "480" width="270"></td>
    <td><img src="image_url" height = "480" width="270"></td>
    <td><img src="image_url" height = "480" width="270"></td>
  </tr>
   <tr>
    <td><img src="image_url" height = "480" width="270"></td>
    <td><img src="image_url" height = "480" width="270"></td>
    <td><img src="image_url" height = "480" width="270"></td>
  </tr>
</table>

**Comment by rob729** [comment]
@nikit19 @liveHarshit I have done the requested changes.

**Comment by rob729** [comment]
@nikit19 I have done the suggested changes.
Please review it.

**Pull request merged**
