### PR TITLE
fix: retain value of time and type of event

### LINKED ISSUE #1567: Retain Event time and type while changing values
**Describe the bug**
Event type and event type changes to the default value on changing either one of them
**To Reproduce**
1. Go to Search Tab
2. Change Time from Anytime to tomorrow
3. Now Change Anything to any event type

**Expected behavior**
The fragment should retain both the values but instead, it resets one of the values

videotogif_2019 04 08_22 59 34

**Would you like to work on the issue?**
- [x] Yes

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Fixes #1567 

Changes: Saved Time and event type to shared preferences

Screenshots for the change:

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal I can only work on #1561 after this has been merged so please review this ASAP

**Comment by iamareebjamal** [comment]
Peer reviews please

**Comment by aggarwalpulkit596** [comment]
@liveHarshit please review

**Comment by aggarwalpulkit596** [comment]
@liveHarshit any update

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal please merge so that I can start working #1561

**Pull request merged**
