### PR TITLE
Issue #802 Searching Feature in Map removed

### PR DESCRIPTION
**Pull request by harshitagupta30**
Fixes issue #802

Screenshots for the change: 
screenshot_2017-01-25-20-30-13
screenshot_2017-01-25-20-30-18
screenshot_2017-01-25-20-30-28

### CODE REVIEW

**Comment by free4murad** [comment]
@harshitagupta30 
The share message doesn't make any sense.
I think should be no overflow menu in the map activity.
Just a suggestion.

**Comment by harshitagupta30** [comment]
@free4murad Actually it was there in the app which is on playstore. 
@mananwason Kindly let me know whether to keep the share option or remove it. :)

**Comment by free4murad** [comment]
@harshitagupta30 @mananwason 
i think that share button in map fragment is currently useless and should be removed.

**Comment by harshitagupta30** [comment]
@mananwason @the-dagger Can you please tell me if the share option at the top need to be kept or removed from the menu?

**Comment by the-dagger** [comment]
No need to remove the share option, lets keep it there.

**Pull request merged**
