### PR TITLE
changed listview to gridview in sponsors fragment.

### PR DESCRIPTION
**Pull request by sahithi-rv**
grid

### CODE REVIEW

**Comment by creativepsyco** [comment]
Please clean up the pull request, it contains a merge commit.

**Comment by mananwason** [comment]
Also @creativepsyco I think this doesn't look really good. The logos are all out of proportions. I think we should keep it as a Recycler view only.

**Comment by creativepsyco** [comment]
@mananwason yes recycler view supports `GridLayoutManager`  no need to use a GridView.

**Comment by mananwason** [comment]
okay then I am closing this PR @creativepsyco.

**Pull request closed without merging**
