### PR TITLE
Improved UI of TracksActivity(TrackSessionsActivity now)

### PR DESCRIPTION
**Pull request by brainbreaker**
- Renamed the TracksActivity to TrackSessionsActivity
- Improved the user interface of TrackSessionsActivity

Fixes issue #1037

### CODE REVIEW

**Comment by mananwason** [comment]
@brainbreaker Can you please reuse these icons instead of adding new ones? All these icons are being already used in the project I believe.

**Comment by brainbreaker** [comment]
@mananwason Okay, I actually added the latest bookmark one from Google's official material icons library, also the other two 'Date Range' and 'Access time white' is not available in drawables. Should I reuse the bookmark one? 
I actually liked the new one so went for it, lol.

**Comment by the-dagger** [comment]
@brainbreaker You are free to add new bookmarks, but make sure to delete duplicate old ones too.

**Comment by anuradhagupta345** [comment]
@brainbreaker Please resolve merge conflicts!

**Pull request merged**
