### PR TITLE
Fixes #1551 : Auto disappearance of map icon

### LINKED ISSUE #1551: Handling of map icon click of SessionDetailActivity and LocationActivity
**Actual Behaviour**

Currently the map icon click for both activities are creating problems.
For sessiondetail activity the map icon is disappearing and for location activity the map icon is disappearing along with map icon click issues encountered in it.

**Expected Behaviour**

Resolve these errors

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/24

### PR DESCRIPTION
**Pull request by rohanagarwal94**
Partially fixes #1551

Changes: The map fragment was not being deregistered on back pressed. Only its view was being removed. Hence the action bar on back pressed belonged to the map fragment and not the sessionsdetail Activity. @mahikaw Might be the same problem in locations activity. Please complete the WIP.

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
@iamareebjamal please review.

**Comment by mahikaw** [comment]
@rohanagarwal94 I was already working on this issue and there is already an ongoing PR #1551 for the same. In future if you intend to work on any issue, I request you to please make it clear on that issue/PR. 
This is a good practice, just to ensure that **developers don't waste time working on the same issue.** 
I'm not sure what to do with the current PR #1551 in progress.
@iamareebjamal shall I edit it to address the partial issue that has been solved already or continue with my work there?

**Comment by iamareebjamal** [comment]
@mahikaw Please continue with your work as you started it first. I think this is the best way

**Comment by arp95** [comment]
@rohanagarwal94 please take care of this as @mahikaw is totally right on this.

**Comment by rohanagarwal94** [comment]
@mahikaw I have no intentions of wasting anyone's time. It collectively affects everyone. Since you were partially solving the issue (in the locationActivity), I tried solving the other half (in the sessionsDetailsActivity).

**Comment by iamareebjamal** [comment]
But you could have told her that you intend to do so or just tell her the fix as she was assigned on the PR. Nevertheless, let's not turn it into any more fuss

**Comment by mahikaw** [comment]
@rohanagarwal94 I would request you to re-read the issue. It is about addressing both the activities. There is no need to create different PRs for the same issue just because they are in different activities in my opinion. However, @iamareebjamal is right, let's continue working together and improve this project on a whole. 🙂

**Comment by rohanagarwal94** [comment]
closing this since it is solved in #1645

**Pull request closed without merging**
