### PR TITLE
Revert "Code improvements optimizations"

### PR DESCRIPTION
**Pull request by the-dagger**
Reverts fossasia/open-event-android#725

### CODE REVIEW

**Comment by the-dagger** [comment]
@PareshMayani This Build is passing correctly.
[https://travis-ci.org/fossasia/open-event-android/builds/167873328](https://travis-ci.org/fossasia/open-event-android/builds/167873328)

**Comment by PareshMayani** [comment]
Have you found the exact solution? Reverting back is not the solution. And now enjoy squash merging :(

**Comment by the-dagger** [comment]
@PareshMayani I have reverted back for now and I'll see as to what is the root cause of this problem by changing all the support libs once by one.
Also for merge, I did a squash merge for this PR because a normal merge would have created 2 commits, one for the PR's commit and one commit for me merging this PR which I thought wasn't a good thing.
What do you think?

**Comment by PareshMayani** [comment]
Merge commit is not an issue, we can do cherry pick and only send required commits! but squash merge is not the standard way because as I said earlier this way you will lose commits history!

And about merge commits, it is a normal scenario when there are multiple people working on the same codebase.

**Comment by mariobehling** [comment]
@PareshMayani Thanks for your input. This project is still young and we are all learning. So @the-dagger is doing an excellent job of keeping the project moving forward. We surely need to improve on the processes as well, but we also need to continue moving forward. Please help to shape the project and we will figure out the best ways. Your comments are really helpful, though I am also not sure about best practices. At the beginning of the project @juslee set policies for pull requests. Let's move forward now together and figure out how we do it in future. Cheers.

**Comment by PareshMayani** [comment]
Hey @mariobehling thank you for the comment. Currently I am trying to update/optimize minor issues, once I am done with that, will start pushing commits, issues and PRs for UI improvements which is badly required!

**Pull request merged**
