### PR TITLE
fix: After coming back from result detail, search result come back to the top, not current position #1150

### LINKED ISSUE #1150: After coming back from result detail, search result come back to the top, not current position
**Describe the bug**
When users try click on a search result and then click back button, the search result doesn't stay at the same position but get to the top

** Images & Gif **
Gif link: https://i.ibb.co/Qmb3Cwv/video-1550686001.gif (file too large, cannot upload to issue)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Nokia 7 Plus|
|Android Version| Android 9 API 28 |

**Would you like to work on the issue?**

<b>Yes </b>

### PR DESCRIPTION
**Pull request by anhanh11001**
Details: 
I checked if the view is already initialized. If it is, I reuse the view of the search result, not reload the whole thing again. I also realized that the events fragment have the same problem so I make the same change.

Besides, I prevent the change in action bar by setting the action bar first before rendering the rootView

Fixes #1150 

Screenshot:

### CODE REVIEW

**Comment by anhanh11001** [comment]
@liveHarshit I have fixed the problem that you found on the last PR I made on issue #1150, please review

**Comment by anhanh11001** [comment]
After testing out again, I realized I made a mistake. So I changed the EventsFragment by checking if rootView is already initialized and if it is not redirected from SearchLocationFragment (new search). If it is already initialized and not a new search, the old rootView is reused. Please review again. Thank you.

I attached a video cap screen below. It's around 40s so I cannot capture it into a gif

https://www.youtube.com/watch?v=looVjPgAFPk

**Comment by anhanh11001** [comment]
Sorry I made a mess with a lot of commit here, I will open another cleaner PR with the same content

**Comment by liveHarshit** [comment]
> Sorry I made a mess with a lot of commit here, I will open another cleaner PR with the same content

Please do not close PR and send new PR for the same issue.

**Comment by anhanh11001** [comment]
@liveHarshit sorry, I did, is it a big problem?

**Pull request closed without merging**
