### PR TITLE
styles done

### LINKED ISSUE #372: Abstract styles from app components facilitate #371
We need to have styles for each and every component of the app so that we can create a script to change these styles according to organiser preferences. After we achieve this we can use the output of this in our app generator page ( #371) to generate a customised apk for an event.

### PR DESCRIPTION
**Pull request by mananwason**
@the-dagger Please review and merge. This resolves #372

### CODE REVIEW

**Comment by mariobehling** [comment]
Travis is failing and codacy test is not performing. Any idea why there are no codacy tests?

**Comment by the-dagger** [comment]
@mariobehling travis is failing because styles.xml was not properly defined.
And for codacy and codecov, i'm working on getting them back.
Seems like the branch merge affected them.

**Comment by mananwason** [comment]
@the-dagger Please review. This has been fixed already and build is passing

**Comment by the-dagger** [comment]
Sorry, I was a bit busy.
Will review now

**Comment by mananwason** [comment]
Great 👍

**Pull request merged**
