### PR TITLE
fix : Information lost on repetitive clicking of SignUp button in bottom navigation bar

### LINKED ISSUE #608: Information lost on repetitive clicking on SignUp button on navigation bar
**What is the issue about ?**
I'm not sure whether this is considered as an issue or not, please look into it. 
When we fill credentials in signup fragment and click on SignUp button in bottom 
navigation bar, all the filled information is lost. 

**Screen-Shots**
whatsapp image 2018-10-01 at 10 39 21 pm

**Would you like to work on this issue?**
Yes (I want mentors to approve this issue so that I can start working on it!)

### PR DESCRIPTION
**Pull request by shikhart98**
fixes #608

### CODE REVIEW

**Comment by iamareebjamal** [comment]
We are actually already working on this issue. We'll see which implementation is better and merge the one accordingly

**Comment by shikhart98** [comment]
@iamareebjamal I think you should merge this PR for now. If you find any better implementation you can always put an issue for this later.

**Comment by iamareebjamal** [comment]
That's counter productive> Why would we merge something just to revert or replace it later?

**Comment by iamareebjamal** [comment]
@simarsingh24 You had the fix ready for retaining the fragments, right? Can you please send a PR

**Comment by simarsingh24** [comment]
@shikhart98 is the issue still active after the last PR that got merged (retaining fragments). If yes please share a gif of the same and also update the PR otherwise please close this. Thanks

**Comment by shikhart98** [comment]
I'll send it by tonight!

**Comment by shikhart98** [comment]
@simarsingh24  I tried running the the app, the problem is still there.

**Comment by simarsingh24** [comment]
@shikhart98 could you please attach a gif for the same

**Comment by shikhart98** [comment]
@simarsingh24 
I think it is not yet solved.
ezgif com-video-to-gif 1

**Comment by shikhart98** [comment]
@simarsingh24 any update on this?

**Comment by simarsingh24** [comment]
@shikhart98 see why error or toast are not displayed. please proceed

**Comment by iamareebjamal** [comment]
The problem is that the fix applied by @simarsingh24 was just in MainActivity, follow the same approach in AuthActivity

**Comment by shikhart98** [comment]
Can I do it?

**Comment by iamareebjamal** [comment]
Yes

**Pull request closed without merging**
