### PR TITLE
fix: Data Loss on Rotating Screen #1191

### LINKED ISSUE #1191: Data Loss on Rotating Screen
**Describe the bug**
In TicketsFragment, changes on Spinner is not retained when rotating

**Screenshots**
Before rotating:

After rotating:

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by aman210697**
Fixes #1191 

Changes: ticketIdAndQty hashmap in ticketviewmodel to retain the value, new functions (handleTicketSelect,totalTicketsEmpty) in ticketviewmodel , modify bind func in TicketViewHolder

Screenshots for the change:
whatsapp image 2019-03-04 at 1 54 41 pm 1
whatsapp image 2019-03-04 at 1 54 41 pm

### CODE REVIEW

**Comment by angmas1** [comment]
Make sure travis build passes.

**Comment by aman210697** [comment]
> Make sure travis build passes.

what could go wrong?

**Comment by angmas1** [comment]
Click on details and go down to bottom understand the error and make necessary changes

**Comment by pranavpandey1998official** [comment]
there is already a pr for this issue #1099

**Comment by iamareebjamal** [comment]
I am seeing strange and unrelated changes

**Comment by aman210697** [comment]
@nikit19 @iamareebjamal passed all checks, please review it

**Pull request closed without merging**
