### PR TITLE
feat: add charge model and API

### LINKED ISSUE #309: Implement Charges API,Model etc
working on it

### PR DESCRIPTION
**Pull request by nikit19**
fixes #309

### CODE REVIEW

**Comment by simarsingh24** [comment]
add chargesAPI to modules.kt too

**Comment by nikit19** [comment]
PR updated

**Comment by dreadpool2** [comment]
@nikit19 travis is failing

**Comment by nikit19** [comment]
PR updated it was because since I am not using the `@id` in the data class I cannot add it to JSONAPI factory

**Pull request merged**
