### PR TITLE
fix: Add icon support for JPEG (deprecated)

### LINKED ISSUE #1701: Convert JPEG icons to PNG
**Actual Behaviour**

App generator crashes due to `None` quality for JPEG icons

**Expected Behaviour**

There should be an option for generator to convert JPEG to PNG in generator

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #1701

Changes: 
- Adds support for JPEG launcher icons by converting them to PNG

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@niranjan94 Please review

**Comment by iamareebjamal** [comment]
@niranjan94 said that we should not support JPEG. So, changing it along the lines to notify the user that your build failed due to the icon being JPEG

But later as currently, there are more pressing issues

**Comment by arp95** [comment]
i think this is important. we cant restrict the event organiser to provide png logo. this should be taken care of.

**Comment by niranjan94** [comment]
@arp95 then we should be doing a conversion to png in the generator if it is not png.

**Comment by iamareebjamal** [comment]
Yeah, changing to this

**Comment by iamareebjamal** [comment]
@niranjan94 Please review

**Pull request merged**
