### PR TITLE
Merge development to master

### PR DESCRIPTION
**Pull request by mananwason**

### CODE REVIEW

**Comment by mariobehling** [comment]
@mananwason Again, you merged a pull request of yourself without peer review and with failing build tests. What is going on?

**Comment by mananwason** [comment]
@mariobehling I did this merge from the command line and the PR had merge conflicts. If I solved conflicts and pushed commits before merge, they'd have changed the files on the development branch as well, which we didn't want. So, I did a merge locally and then pushed to master.

**Comment by mariobehling** [comment]
@mananwason The workflow is clear and there should not be merge conflicts if you follow the flow. I do not know if you based it on an old master version or what happened and I do not think it is my responsibility to research what you did now. The outcome in any case cannot be that the master branch is ahead of development. As a matter of fact this can create conflicts in merges from dev to master.

**Comment by mananwason** [comment]
I understand @mariobehling. I did follow the flow and I used the solutions provided by git documentation but there were some commits in the history after the pull request by @the-dagger that corrupted the history. I have made sure that only the commits that are required are on the branch but the merge commit shows that it's ahead of development. I am trying to figure out why this is happening.

**Pull request merged**
