### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by mRokita**
GCI task: https://codein.withgoogle.com/dashboard/task-instances/5039945412509696/
I've also replaced hardcoded strings in res/menu/drawer.xml to string resources to make the translations work.

### CODE REVIEW

**Comment by championswimmer** [comment]
Screenshot as shared by @mRokita 
src

**Comment by championswimmer** [comment]
@mananwason @batraabhishek the app builds. The errors are in testing. We can merge this.

**Comment by creativepsyco** [comment]
:+1:

**Comment by creativepsyco** [comment]
I assumed the merge was okay, apparently not, my bad, @mRokita can you make a new PR with the changes?

**Pull request merged**
