### PR TITLE
Use a better nav_drawer image when the app is offline

### PR DESCRIPTION
**Pull request by the-dagger**
Fix for #285 
When the app is offline, the nav_header image is set as twitter logo.
I modified it to use the fossasia logo from the splash screen.
@mananwason @championswimmer 
alt tag

### CODE REVIEW

**Comment by mananwason** [comment]
@the-dagger I didn't want to increase the apk size by adding more resources. Plus the main aim of the system is to be __Event independent__ and if we add such logos, then it defeats the purpose.

**Comment by the-dagger** [comment]
@mananwason Understood!
Should we set the default image to be a solid material color?

**Comment by mananwason** [comment]
@the-dagger I would prefer just removing the twitter image and let it be same as the drawer color. If we set any particular material color, then also it amy be different from what the conference theme is.

**Comment by the-dagger** [comment]
Aight then. (y)

**Pull request closed without merging**
