### PR TITLE
docs: Updated screenshots.

### LINKED ISSUE #1247: Updating screenshots in readme.md
Some screenshots in `readme.md` are outdated.

@the-dagger 
I am sending a PR for this.

### PR DESCRIPTION
**Pull request by free4murad**
Fixes #1247 

Changes: I have updated screenshots in `readme.md`.
I have used cloud.githubusercontent for saving images. I have used this because saving binary files in a repo unnecessarily bloats it. Using Images form cloud.githubusercontent will increase the size of repo.

Screenshots for the change: 
Tracks
tracks

Schedule
schedule

Speakers
speakers

Sponsors
sponsors

Locations
location

Speaker
speaker

Session List
session-list

Session
session

### CODE REVIEW

**Comment by free4murad** [comment]
@the-dagger @mananwason 
Please review the PR.

**Comment by mananwason** [comment]
Add one with the maps too

**Comment by free4murad** [comment]
Map
map

**Comment by free4murad** [comment]
@mananwason 
Done

**Comment by free4murad** [comment]
@the-dagger 
please review and merge

**Comment by the-dagger** [comment]
Thanks

**Pull request merged**
