### PR TITLE
fix: Remove extra space in settings.

### LINKED ISSUE #873: Remove extra space in Settings screen.
**Describe the bug**

Extra space is present before options in the Settings Screen of the app.

**To Reproduce**

Go to the settings screen to see.

**Expected behavior**

There should be no extra space present before options in the preference screen.

**Screenshots**

padding

**Smartphone Info:**

|Device         |One Plus 5|
|Android Version|Android Pie 9.0.0 |

**Additional context**

@iamareebjamal @nikit19 Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by angmas1**
Fixes #873 

Changes: Updated library to google's preference library with fix for bug that didn't let app:iconSpaceReserved to get applied to PreferenceCategory. For more info visit: https://issuetracker.google.com/issues/111662669#comment19

Screenshots for the change:
image

### CODE REVIEW

**Comment by angmas1** [comment]
@iamareebjamal @nikit19 Please review.

**Comment by iamareebjamal** [comment]
We used takisoft so that preferences look same in KitKat as well. Please check how does it look there

**Comment by angmas1** [comment]
Okay. Will post a screenshot

**Comment by angmas1** [comment]
Just tried running the app on API 19 (Kitkat) and found out that the current development branch of app(not the one associated with this pull request) crashes on kitkat. Should I open an issue for that? @iamareebjamal

**Comment by iamareebjamal** [comment]
Yes

**Pull request merged**
