### PR TITLE
Improving the search facility in map for play version

### PR DESCRIPTION
**Pull request by heysadboy**
Fixes https://github.com/fossasia/open-event-android/issues/1637

- Improving the search UX by providing the user facility to select the location instead of typing and clearing up the views earlier present on the map fragment.
- Putting up the search button it toolbar.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@heysadboy Please provide screenshots

**Comment by heysadboy** [comment]
@iamareebjamal These changes are for Google Play variant only, for which I have attached screenshots in the issue. Clicking on search button on toolbar goes like this,

<table>
<td>

</td>
<td>

</td>
</table>

**Comment by iamareebjamal** [comment]
@heysadboy Yeah sorry. Forgot to see the Play variant changes

Also mention what you have changed in OSMapFragment as well please

**Comment by heysadboy** [comment]
@iamareebjamal It was a stray button in toolbar to share map, when I removed that from the menu_map.xml to add search option in play version I had to remove that from OSMapFragment to stop the droid version from crashing. I haven't modified any functioning for droid versionother than that.

**Comment by iamareebjamal** [comment]
OK. But now, please create an issue for adding a share button for location sharing and take a look at the suggestion for autocompletetextview

**Comment by heysadboy** [comment]
@iamareebjamal Creating issue for that here https://github.com/fossasia/open-event-android/issues/1659. I considered that initially but I didn't use it because a user may not know about all the locations' textual info. like spelling etc. Selecting from a list was a better option as unlike the name of locations displayed in other fragments, no info. is displayed here.

**Comment by iamareebjamal** [comment]
@the-dagger @mariobehling @mananwason Please suggest

**Comment by mahikaw** [comment]
I agree  that the user might not know all the locations out there. But on the other hand, if there are a large number of locations, this type of list will make it tough for the user to navigate through @heysadboy 

I would suggest to incorporate both. The list will appear when the user has typed nothing and then the search will come into play as soon as user starts typing.

**Comment by heysadboy** [comment]
@mahikaw That's a great suggestion. I think that would be the best of both options.

**Comment by heysadboy** [comment]
@iamareebjamal Making the required changes, I am using AutoCompleteTextView now.
<table>
<td>

</td>
<td>

</td>
</table>

**Comment by iamareebjamal** [comment]
@heysadboy Please remove Mahika's commit from your PR

**Comment by heysadboy** [comment]
@iamareebjamal I tried removing but ended up removing all the commits accidentaly :( , I am really very sorry about this. Please find new one here https://github.com/fossasia/open-event-android/pull/1668

**Pull request closed without merging**
