### PR TITLE
fixes issue #958

### PR DESCRIPTION
**Pull request by arp95**
made changes to ui as follows:

15902662_10210135775065346_1175802889_o 1
16108009_10210219484958041_533561470_o

### CODE REVIEW

**Comment by the-dagger** [comment]
The speaker fragment looks OK to me,  but I'm not sure about the schedule viewpager.
The default ui is good enough, we don't need gridview everywhere.

**Comment by arp95** [comment]
on the tablet view it didnt seem fine.  So should i submit only the changes in speaker then?

**Comment by the-dagger** [comment]
Yes please commit the changes only for speaker fragment.
And as mentioned previously, also have a look at the other
fragments/activities as well if they looked weird on tablet layout and
commit changes for them in this pull request.

I'll put this pr on hold till then.

>

-- 
Best,
Harshit Dwivedi

**Comment by arp95** [comment]
@the-dagger you can have a look at the speakers fragment changes.
According to me all the activities look fine on tablet view. You can have a look now.

**Pull request merged**
