### PR TITLE
App Crashing on bookmarking any session #84 FIXED

### PR DESCRIPTION
**Pull request by opticod**
Its not crashing now. :)

### CODE REVIEW

**Comment by mananwason** [comment]
@opticod Please get rid of the Merge commit. Thanks

**Comment by opticod** [comment]
@mananwason Please review it.I had removed the merge commit. Thank You .  :smile:

**Comment by opticod** [comment]
@mananwason i found one more issue ,if you closes the app completely from 'Recents' and then press the bookmarked notification...the app gets crashed.

**Comment by opticod** [comment]
@mananwason I have resolved both of the issues. Please review it.

**Comment by mananwason** [comment]
@opticod Merging !

**Pull request merged**
