### PR TITLE
progessbar indicating that data is downloading.

### LINKED ISSUE #1490: Show progress of completion while downloading
**Actual Behaviour**

Currently, when the app id downloading data and if we move to the tracks section, it displays "no tracks", as shown below.

**Expected Behaviour**

The screen should indicate that data is downloading.
**Steps to reproduce it**
Go to tracks section soon after starting the app.

**Screenshots of the issue**

screenshot_20170506-143043

**Would you like to work on the issue?**
yes
@mariobehling @the-dagger @mananwason can I work on this issue and send a PR?

### PR DESCRIPTION
**Pull request by mahikaw**
Fixes #1490 

Screenshots for the change: 

device-2017-05-13-175711

### CODE REVIEW

**Comment by iamareebjamal** [comment]
It'd be better is you show the progress of the download as well. Like which part is being downloaded and at which step is the download. Like Downloading Tracks and 1/5 in a progress bar

**Comment by Shailesh351** [comment]
I agree @iamareebjamal .
And i think it will overlap with recyclerview when event data is already downloaded

**Comment by iamareebjamal** [comment]
We can show a downloading dialog so that user doesn't interact with UI until it is fully loaded

**Comment by mananwason** [comment]
@mahikaw as @iamareebjamal said, add a progress dialog to stop the user from interacting. Also, @iamareebjamal I don't think it will be possible to figure out what has been downloaded as the main activity just shows how many downloads have begun. So @mahikaw You can just show the percentage of download done

**Comment by iamareebjamal** [comment]
@mananwason I was talking about using the event bus subscription to show which part of data is being downloaded.

The log shows it like this
```
05-13 21:20:15.882 24584-24711/org.fossasia.openevent D/RealmDataRepository: Saved Tracks
05-13 21:20:15.889 24584-24584/org.fossasia.openevent D/Donecounter: 1 tracks 5
05-13 21:20:16.780 24584-24898/org.fossasia.openevent D/RealmDataRepository: Saved Sessions
05-13 21:20:16.806 24584-24584/org.fossasia.openevent D/RealmDataRepository: Saved Locations
05-13 21:20:17.144 24584-24711/org.fossasia.openevent D/RealmDataRepository: Saved Speakers
05-13 21:20:17.186 24584-24584/org.fossasia.openevent D/RealmDataRepository: Saved Sponsors
05-13 21:20:17.259 24584-24584/org.fossasia.openevent D/Donecounter: 2 microlocation 5
05-13 21:20:17.261 24584-24584/org.fossasia.openevent D/Donecounter: 3 sponsors 5
05-13 21:20:17.261 24584-24584/org.fossasia.openevent D/Donecounter: 4 session 5
05-13 21:20:17.263 24584-24584/org.fossasia.openevent D/Donecounter: 5 speakers 5
05-13 21:20:17.286 24584-24584/org.fossasia.openevent D/MainActivity: Download done
```

The done counter subscription can be used to update progressbar to show downloaded/total component

**Comment by mahikaw** [comment]
I'll redo it  @mananwason @iamareebjamal @Shailesh351  Thanks for reviewing.

**Comment by iamareebjamal** [comment]
@mahikaw Any updates?

**Comment by mahikaw** [comment]
@iamareebjamal sure I'll update the PR 👍

**Comment by iamareebjamal** [comment]
@mahikaw Any updates?

**Comment by mahikaw** [comment]
I'm sorry for delaying. I am a bit caught up with the samples and related issues. Could you do it instead?

**Comment by iamareebjamal** [comment]
OK @mahikaw :+1:

**Comment by iamareebjamal** [comment]
@mahikaw I have taken a different approach to this issue, so opened a new PR instead. #1630 

Please take a look and if it feels okay, please close this one

**Comment by iamareebjamal** [comment]
Created #1630 instead of this

**Pull request closed without merging**
