### PR TITLE
fix: maintaining text size throughout the app

### LINKED ISSUE #1657: Managing text size throughout the app
**Actual Behaviour**

The text size of the locations fragment is bigger than other places in the app e.g., tracks and schedule.

<table>
<td>

</td>
<td>

</td>
</table>

**Expected Behaviour**

I think text should be similar here, with title in darker and sub in lighter shade.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Milestone 5

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1657 

Changes: 

Maintained the text size throughout the app. Also moved all the constant values from layout to dimens.xml.

Screenshots for the change: 

-

### CODE REVIEW

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 @shreyasnbhat @mahikaw @rohanagarwal94 
please review.

**Comment by arp95** [comment]
Screenshots of the app:

19126110_10211557157319014_826379030_o

19179583_10211557157479018_1373840342_o

19197633_10211557157639022_1145044507_o

19212729_10211557157159010_940505243_o

**Comment by shreyasnbhat** [comment]
@arp95 I think bold for the Speaker Title would look better

**Comment by arp95** [comment]
@shreyasnbhat
any other change you think?

**Comment by shreyasnbhat** [comment]
@arp95 And for the Schedule could you do something similar to the Search Speaker ViewHolder. I'm talking I terms of the font sizes.
Rest looks good!

**Comment by arp95** [comment]
@shreyasnbhat i am following a standard approach that is for title its 16dp and for the rest 14dp. i have made the speaker title bold have a look now.

@iamareebjamal @Shailesh351 @rohanagarwal94 @mahikaw 
please review.

**Pull request merged**
