### PR TITLE
refactor: Format xml files with eclipse format

### LINKED ISSUE #1815: Apply spotless for XML resources files
**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #1815 

Formatter preferences - https://github.com/diffplug/spotless/blob/master/spotless.eclipseformat.xml

### CODE REVIEW

**Comment by liveHarshit** [comment]
I have not added it in spotless, because it will make difficult to run spotless before each commit.

**Comment by anhanh11001** [comment]
I'm not sure if I should take a look at all the change, cause it's a lot. From what I understand, the changes were made by the plugin from the library given above ?

**Comment by liveHarshit** [comment]
> the changes were made by the plugin from the library given above ?

Yes, the plugin is already added, but I have not committed the xml configuration because it will rise problem for multiple build failing in future PRs.

**Comment by iamareebjamal** [comment]
Don't make this change. Sometimes, it makes the formatting worse

**Comment by liveHarshit** [comment]
Okay, but here I have done one time changes only, Not added in the spotless plugin.

**Comment by iamareebjamal** [comment]
I know.

**Pull request closed without merging**
