### PR TITLE
added colour schemes

### PR DESCRIPTION
**Pull request by chhavip**
added different colours and themes based on the shades. can be changed with simple java code as required.

### CODE REVIEW

**Comment by creativepsyco** [comment]
Hi @chhavip thanks for the contributions however, can you take a look at https://github.com/fossasia/open-event-android/issues/48 which addresses this more comprehensively. We need a custom scheme that we can a) either generate during compile time for different events or b) at runtime. 

I would like to get the discussion going on there.

**Comment by mananwason** [comment]
Hi @chhavip. Thanks for contributing but since this is an app that can be used by anyone for their event ,we didn't intend to create any particular styles as such, so I'll close this PR. Anyway please look at the other issues and try to solve them.

**Comment by creativepsyco** [comment]
@mananwason @chhavip I have updated the requirements for issue #48 to be more specific to our situation.

**Comment by mananwason** [comment]
Cool @creativepsyco I think I have done most of the work. Let me work on the leftover part and file a PR within this week. Cheers

**Pull request closed without merging**
