### PR TITLE
App crashing on refreshing with no internet and scrolling on speaker's list for large amount of time, both FIXED #88 #121

### LINKED ISSUE #88: App crashes when refreshing on no Internet connection
App crashes when refreshing on no Internet connection

### PR DESCRIPTION
**Pull request by vjs3**
Application was crashing several times on refreshing in offline mode (no internet connection) at various screens such as Speaker List, Tracks, Location etc. Also there is crashing on when we scroll down for the long time in speaker's list.Both of these are now being fixed. #88 #121

### CODE REVIEW

**Comment by vjs3** [comment]
It is being checked in both landscape and portrait mode and working completely fine in both the cases.

**Comment by mananwason** [comment]
@vjs3 please create different PR's for different issues and squash similar commits everytime.

**Comment by vjs3** [comment]
@mananwason I will take care of it from the next time. Do I have to make 2 new pull request instead of this one?

**Comment by mananwason** [comment]
Yes please.

**Comment by vjs3** [comment]
sure I will do that.

**Comment by vjs3** [comment]
@mananwason sorry for such a late reply, do I need to delete this PR and create two new PR's?If yes then please help me out how to proceed in such a case.

**Pull request closed without merging**
