### PR TITLE
feat : Implement sort by tracks option in Schedule Fragment 

### LINKED ISSUE #1414: Add sort by tracks feature in Schedule
**Actual Behaviour**

There are two option for sorting `Start Time` and `Tracks`. But `Tracks` sorts sessions by Title. 

**Expected Behaviour**

`Tracks` should sort sessions by Tracks. And dialog should display option for sorting sessions by title.
So there will be total three options 

- Title
- Tracks
- Start Time

**Screenshot**
 Expected
screenshot_20170414-190343

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Shailesh351**
Fixes #1414 

Changes: 

1. Added Strings for sort by "Title" in arrays.xml and strings.xml

- Renamed string key like , dialog_sort_tracks  --> dialog_sort_by_tracks

2. Added code for sort by Tracks

- Added OnPageChangeListener on ViewPager in ScheduleFragment
because every time we scroll between days `sortType` is not updated across all DayScheduleFragment because onResume methode is not called every time. So i'm calling onResume() method of Fragment in method of OnPageChangeListener

- Added Sort order for Track and rearranged sort orders for better understanding. 

- Renamed SORT_TYPE_ONE --> SORT_TYPE_*FIRST*
because other two options are SORT_TYPE_*SECOND* & SORT_TYPE_*THIRD*.

3. Sorted Sticky headers for tracks in DayScheduleFragment alphabetically
For it i'm executing raw query because  In sessions table track is referenced using track id.
So for sorting alphabetically we have to use tracks table also.
 

Screenshots for the change: 

screenshot_20170414-190343

videotogif_2017 04 14_19 05 45

### CODE REVIEW

**Comment by Shailesh351** [comment]
@the-dagger Please review :smile:

**Comment by iamareebjamal** [comment]
@Shailesh351 Please squash the commits and resolve conflicts. Thanks

**Comment by Shailesh351** [comment]
I will try to resolve conflicts after few days because my final exams are starting from tomorrow.

**Comment by Shailesh351** [comment]
@mariobehling  I  suggest to merge PRs  in ascending order of  number provided by issue tracker, because it will be hard to resolve conflicts if many files has changes.

**Pull request merged**
