### PR TITLE
fix: Replace setting toolbar with setToolbar

### PR DESCRIPTION
**Pull request by angmas1**
Fixes #1490 

Changes: Replaced logic with setToolbar.

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
Also rename the PR title with something like fix: or chore: to pass sematic check

**Comment by angmas1** [comment]
> Also rename the PR title with something like fix: or chore: to pass semantic check

Oh yeah forgot

**Comment by angmas1** [comment]
> There are some more classes in which this method is not used find and refractor all of them

I have replaced them all in #1506 , let me know if there are any left.

**Comment by angmas1** [comment]
@nikit19 @liveHarshit please review

**Pull request merged**
