### PR TITLE
fix: Favorite FAB drawable bug

### LINKED ISSUE #165: favourite fab drawable not changing on adding to favourite
working on it 👍

### PR DESCRIPTION
**Pull request by simarsingh24**
fixes #165

### CODE REVIEW

**Comment by simarsingh24** [comment]
After change gif
videotogif_2018 07 03_22 54 45
@nikit19 @dreadpool2 please review

**Comment by iamareebjamal** [comment]
This is a workaround. Why is Room not triggering listener once the table content is changed

**Comment by simarsingh24** [comment]
@iamareebjamal We are displaying events from local databse and observer is set on that only when we do setFavorite it updates the event store locally which means automatically recycler views should be updated (ideally), this is the second best solution to this bug I could think of, not sure why observer  is not triggered after update also if it gets called 
```
eventsViewModel.events.observe(this, Observer {
            it?.let {
                eventsRecyclerAdapter.addAll(it)
                eventsRecyclerAdapter.notifyDataSetChanged()
            }
            Timber.d("Fetched events of size %s", eventsRecyclerAdapter.itemCount)
        })
```
then according to this even if a single event is updated all of the events will be inserted once again which should not happen

**Comment by iamareebjamal** [comment]
> even if a single event is updated all of the events will be inserted once again which should not happen
It should happen

There is no point of using Flowable from Room if we're gonna do it this way

There's a reason database is the single source of truth

**Pull request merged**
