### PR TITLE
fix: google map fixed.

### LINKED ISSUE #1167: Issue with Map.
**Actual Behaviour**

Map is showing nothing for googlePlay flavor of the app. 

**Expected Behaviour**

Map should show the location of the venue.

**LogCat for the issue**

screen shot 2017-02-25 at 10 42 26 pm

**Would you like to work on the issue?**

Yes,
We need to update the Maps API key.
But that will link the app to my account on Google.

@the-dagger what should I do?

### PR DESCRIPTION
**Pull request by free4murad**
Fixes #1167

Changes: Google maps are working fine now.

### CODE REVIEW

**Comment by betterclever** [comment]
@free4murad Refer #1253. API key must not be present in code.

**Comment by free4murad** [comment]
@betterclever @mananwason 
Is there any other way of adding a API key in the source code?
I could not find any.

**Comment by betterclever** [comment]
@free4murad Why do you wish to add? Whenever you are testing, you may add your API key.

**Comment by free4murad** [comment]
@betterclever 
got your point.

**Pull request closed without merging**
