### PR TITLE
fix: Add proper Koin Documentation

### LINKED ISSUE #1258: Koin Documentation Link
**Describe the chore**
Replace the current link to proper koin documentation link.

**Would you like to work on the issue?**

- [x] Yes

### PR DESCRIPTION
**Pull request by somenath1435**
Fixes #1258 
Changes: Proper Koin Documentation Link is added in Readme

### CODE REVIEW

**Comment by somenath1435** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
We are linking github repos, not documentations

**Comment by somenath1435** [comment]
@iamareebjamal It is written: "Libraries used and their documentation"

**Comment by iamareebjamal** [comment]
No problem

**Pull request closed without merging**
