### PR TITLE
fix: Thumbnail NullPointerException check

### LINKED ISSUE #1517: NullPointerException on thumbnail parsing
**Actual Behaviour**

Some speaker thumbnails are null and thus cause NPE

**Expected Behaviour**

Null checks should be added in Speaker Adapter and Session Speaker Adapter

**Steps to reproduce it**

Go to Speaker Fragment and sort by organisation and search 'Ho'
App will crash

**LogCat for the issue**

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.openevent, PID: 6912
                                                                      java.lang.NullPointerException: uriString
                                                                          at android.net.Uri$StringUri.<init>(Uri.java:475)
                                                                          at android.net.Uri$StringUri.<init>(Uri.java)
                                                                          at android.net.Uri.parse(Uri.java:437)
                                                                          at org.fossasia.openevent.adapters.SpeakersListAdapter.onBindViewHolder(SpeakersListAdapter.java:99)
                                                                          at org.fossasia.openevent.adapters.SpeakersListAdapter.onBindViewHolder(SpeakersListAdapter.java:36)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                          at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                          at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                          at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1648)
                                                                          at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:343)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:618)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6169)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Would you like to work on the issue?**

Yes. Sending PR

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #1517

Changes:
- Add null checks on thumbnail

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@arp95 This was rare as thumbnail is require field for API. But yes, it may be happening in SessiomnSpeakerListAdapter as well

**Comment by iamareebjamal** [comment]
OK. Sure

**Comment by iamareebjamal** [comment]
Done @mananwason

**Comment by mananwason** [comment]
@iamareebjamal LGTM but please rebase as branch is out of date now.

**Comment by iamareebjamal** [comment]
@mananwason Done

**Pull request merged**
