### PR TITLE
fix: improved the layout of about_event fragment

### PR DESCRIPTION
**Pull request by pranavpandey1998official**
introduced scroolView and removed old collapsingtoolbarlayout and added function to set action bar title

fix: #1014 

screen shot

about2
about1

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please create an issue to strip all tags from the content coming from backend and then show it

**Comment by pranavpandey1998official** [comment]
@iamareebjamal  mean html tags

**Comment by iamareebjamal** [comment]
Yes it is but we can strip them idempotently, for new and old events since there is no timeline when or if server will solve this issue

**Comment by iamareebjamal** [comment]
Both of above issues talk about displaying HTML and links. We are not going to do that. We will be changing HTML to plain text

**Comment by pranavpandey1998official** [comment]
@iamareebjamal @nikit19 please review it

**Pull request closed without merging**
