### PR TITLE
fix: display placeholder image for event

### LINKED ISSUE #1289: No placeholder image for events
**Describe the chore**

No placeholder image is being displayed for events having no image and instead a white blank space is present.
The default placeholder image should be used in such a case

New Issue

It should look something like this
New PR

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by addiegupta**
Fixes #1289.

Changes: 
Instead of displaying the placeholder image only in the layout editor by using the namespace "tools" , the android namespace is used to display the placeholder image by default
Additional changes:
- Removed old placeholder image that is not being used
- Collapsed empty tag for FrameLayout in content_event.xml

Screenshots for the change:
New PR

Edit: As requested by @iamareebjamal , placeholder image has been updated

PR 1290

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This should not be the placeholder image. Take the one used in open event orga app

**Comment by addiegupta** [comment]
I have updated the placeholder image @iamareebjamal

**Comment by aman210697** [comment]
> I have updated the placeholder image @iamareebjamal

How about using Picasso to set placeholder?

**Comment by iamareebjamal** [comment]
Yes it should be used

**Comment by addiegupta** [comment]
@iamareebjamal using Picasso to set the placeholder results in some imageview being empty while in some the placholder is applied. Should I add Picasso placeholder and set src in XML as well?

**Comment by iamareebjamal** [comment]
Yes

**Comment by addiegupta** [comment]
@iamareebjamal  updated

**Pull request merged**
