### PR TITLE
Improving the spanish support

### PR DESCRIPTION
**Pull request by Heredroky**
With this PR, I improved the spanish support. If you have a doubt about the translations, my mother tongue is Spanish 😝  🇨🇴

### CODE REVIEW

**Comment by Heredroky** [comment]
@mariobehling What do you think?

**Comment by Heredroky** [comment]
@mariobehling What do you think?

**Comment by Heredroky** [comment]
@mariobehling Can this be merged?

**Comment by the-dagger** [comment]
Looks good, thanks

**Pull request merged**
