### PR TITLE
Added code for packaging json files and png icons Fixes #557

### LINKED ISSUE #557: Package uploaded json files in the generated apk
* [x] Check if json files are uploaded
* [x] If yes unzip them and package in the assets folder of the generated apk.

### PR DESCRIPTION
**Pull request by mananwason**
@mariobehling @the-dagger Please review. This adds functionality of packaging uploaded json files which was removed by @the-dagger in https://github.com/fossasia/open-event-android/commit/cd2066ffea6a731d0c28f38990e25152a79cee45#diff-4aecd7c485fe4edb2e535ac689de2b07L57.

This also adds functionality of packaging icons to the app which are in the uploaded in the zip.
Fixes #557

### CODE REVIEW

**Comment by the-dagger** [comment]
@mananwason I tried using this with the EHealth samples [https://github.com/fossasia/open-event/blob/master/sample/EhealthAfrica.zip](https://github.com/fossasia/open-event/blob/master/sample/EhealthAfrica.zip) and it doesn't seems to work.
Could you check it out?

**Comment by mananwason** [comment]
@the-dagger You need all the files to have ```.json``` with all the json files. By default the EHEALTH files don't have this. Did you add it?

**Comment by the-dagger** [comment]
@mananwason No, I did not.
Seems like the samples are missing `.json` from them@aviaryan could you please have a look at this?

**Comment by mariobehling** [comment]
>  packaging icons to the app which are in the uploaded in the zip.

I don't know where is the feature request in an issue and how is this implemented.

**Pull request merged**
