### PR TITLE
fix: UI bug in session card in SpeakerDetailActivity

### LINKED ISSUE #1213: Ui bug in session detail card in SpeakerDetailActivity
**Actual Behaviour**

screenshot_20170302-152854
screenshot_20170302-222916

**Expected Behaviour**
Setting maxlines =2 and ellipsize the text at the end.
screenshot_20170302-223622
screenshot_20170302-223608

**Would you like to work on the issue?**
@the-dagger Please review! :+1:

### PR DESCRIPTION
**Pull request by harshitagupta30**
Fixes #1213 

Screenshots for the change: 
screenshot_20170302-223622
screenshot_20170302-223608

### CODE REVIEW

**Comment by mananwason** [comment]
Not facing this issue.

**Comment by harshitagupta30** [comment]
@mananwason Earlier I checked on Asus Zenfone2 API Level 23 
Now screenshots for Nexus5x API Level 23 

screenshot from 2017-03-05 00 27 09

**Comment by mananwason** [comment]
Could you please explain what;s the issue here?

**Comment by harshitagupta30** [comment]
@mananwason In the card's layout, the title's height is set to wrap content due to which it's displaying the entire text but the available space is not sufficient to display it so it goes beyond the layout since the parent layout has defined the height of 100 dp due to which some portion of text is visible while remaining got hidden.

**Comment by harshitagupta30** [comment]
Also there is a field called subtitle which always remains empty which is just above the tracks in the card. Can we remove it?

**Comment by harshitagupta30** [comment]
@mananwason @the-dagger This is how it'll look after removing subtitle which is empty.
screenshot from 2017-03-05 10 54 27

**Comment by mananwason** [comment]
@harshitagupta30 Now I understand. I didn't notice this at first. Look good.

As for subtitle, it's an empty screen right now but we want to keep it this way.

**Pull request merged**
