### PR TITLE
Added Share speaker info intent

### PR DESCRIPTION
**Pull request by Yathannsh**
Preview:
capture

### CODE REVIEW

**Comment by creativepsyco** [comment]
Why would you want to share speaker name & email I don't get it.

**Comment by Yathannsh** [comment]
@creativepsyco this [task] (https://codein.withgoogle.com/dashboard/task-instances/6044499427983360/?sp-page=1) required adding a feature to share speaker's name & email.
Let me know if this is not what was expected and I shall improvise. Thanks!

**Comment by creativepsyco** [comment]
I will have concerns if someone shared my email publicly. I think a better way would be to share the speaker's image and the content of the caption can be something like **Mr. X is speaking in event Y on topic etc. etc. For more info checkout app on GOOGLE-PLAY-APP-STORE-LINK**

Maybe something like this: image

Instead of `share a photo` have your own composed text.

**Comment by Yathannsh** [comment]
Sure! I will try and implement this! :+1:

**Comment by Yathannsh** [comment]
@creativepsyco  @mananwason 
I am working on implementing the suggested feature.
There is one problem I am facing, that is as the images are downloaded as links sending them to Facebook will work as the github avatar link is rendered and the image is displayed. However this does not work for other apps. What to do?
Implementation for Facebook:
558b35b1-3f11-44c8-8091-41adc3b781b3

**Comment by Yathannsh** [comment]
Also not sure if this is a bug in the app or a database problem.
But, the images and speaker's name do not correspond. 
8cf0aba4-751e-45b3-8ec9-6570779fddf9

**Comment by shivenmian** [comment]
That's a server problem, that's no issue.

**Comment by creativepsyco** [comment]
I mean if you know the URL you can still in theory download the image and provide it via `text/stream` intent which can then be read by facebook to do the upload.

**Comment by Yathannsh** [comment]
Thanks for the clarification @shivenmian :+1: 
@creativepsyco I did try that, but am unable to convert the URL to bitmap and then share it via an intent. For now I will submit the rudimentary section for sharing speaker's information as you suggested. Senior developers can then further help integrate image sharing via <code>text/stream</code>

**Pull request closed without merging**
