### PR TITLE
chore: add scripts to automate playstore release

### LINKED ISSUE #270: Use fastlane to release the app in alpha
working on it

### PR DESCRIPTION
**Pull request by nikit19**
fixes #270

### CODE REVIEW

**Comment by nikit19** [comment]
@iamareebjamal Please review and could you add the required API keys for fastlane as well whenever you get time

**Comment by nikit19** [comment]
@iamareebjamal I think I just need to uncomment the lines where the environment variables are required and this should be good to go. Otherwise please suggest changes

**Comment by iamareebjamal** [comment]
The tar file is not uploaded yet. I'll upload it today

**Comment by nikit19** [comment]
@iamareebjamal Could you please add the tar file whenever you get time

**Comment by nikit19** [comment]
@iamareebjamal is testing it by merging dev into master a bad idea ?
If the commands are working in other repos I guess it should work here too

**Comment by iamareebjamal** [comment]
Other repos are not using the mv commands used here

**Comment by nikit19** [comment]
@iamareebjamal where is the `mv` command being used ?
And how is this code different from the orga app ?

**Comment by iamareebjamal** [comment]
`update-apk.sh`

**Comment by simarsingh24** [comment]
@iamareebjamal i can find usage of mv command inside `update-apk.sh` ? did you mean `cp`?

**Comment by iamareebjamal** [comment]
If cp is being used there, convert to mv

**Comment by simarsingh24** [comment]
@iamareebjamal  https://github.com/fossasia/open-event-orga-app/blob/development/scripts/update-apk.sh in orga app they are also using `cp` do you want me to change` cp` to `mv` in `update-apk.sh`

**Comment by iamareebjamal** [comment]
Yes there are duplocate apks being generated. What's the use of `app-debug-release` and `open-event-dev-app-debug-release` if both are same

There should only be one

**Comment by simarsingh24** [comment]
@iamareebjamal looking into it

**Pull request merged**
