### PR TITLE
Fixed SessionDetailActivity AppBarLayout not collapsing

### PR DESCRIPTION
**Pull request by omar753sahl**
Fixed issued #1407 "SessionDetailActivity AppBarLayout not collapsing appropriately"

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Your commit also changes build.gradle and gradle.properties. If you want to update it, please open another issue and send PR for it. Your PR should have 1:1 correspondence with the issue. 
Secondly, it is better if you follow the PR template and document what did you change in the PR, it makes review process easy

**Comment by omar753sahl** [comment]
Where can I find the PR template?

**Comment by the-dagger** [comment]
Omar, that you can see when you open a new PR.
There is some placeholder text that you have to edit and add some
text/screenshots accordingly.

Best,
Harshit Dwivedi
Contact : +919968195588
GitHub <https://github.com/the-dagger> | LinkedIn
<https://in.linkedin.com/in/hadwivedi>
Google Play <https://goo.gl/wl3loD> | Facebook
<https://www.facebook.com/daggerdwivedi>

**Comment by omar753sahl** [comment]
Ok, thank you
I guess I didn't see it because I created the PR from the GitHub desktop app.

**Comment by free4murad** [comment]
@omar753sahl
one PR must solve only one issue. 
Also, there should be one commit per PR.

**Comment by omar753sahl** [comment]
OK, I created a new Issue for the Gradle update.
and I will create a new PR for the AppBarLayout Issue.

**Pull request closed without merging**
